/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:39011'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:34795'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:43844'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:40603'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:39408'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:43260'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:38414'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:35287'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:40635'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:41356'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:45615'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:32915'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:35551'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:34825'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:46682'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:45443'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:41600'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:45884'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:37497'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:40939'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:38745'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:44863'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:34629'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:39151'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:33107'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:40056'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:44984'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.9:39733'
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:40185
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:40185
distributed.worker - INFO -              nanny at:          172.30.10.9:45615
distributed.worker - INFO -              bokeh at:          172.30.10.9:32867
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-xeoj58d5
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:46211
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:46211
distributed.worker - INFO -              nanny at:          172.30.10.9:41356
distributed.worker - INFO -              bokeh at:          172.30.10.9:38295
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-af8d4b2f
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:44158
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:44158
distributed.worker - INFO -              nanny at:          172.30.10.9:41600
distributed.worker - INFO -              bokeh at:          172.30.10.9:44502
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-1sjtf3k8
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:37023
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:37023
distributed.worker - INFO -              nanny at:          172.30.10.9:39733
distributed.worker - INFO -              bokeh at:          172.30.10.9:41720
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-7jmvmw0f
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:36962
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:36962
distributed.worker - INFO -              nanny at:          172.30.10.9:34795
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:38520
distributed.worker - INFO -              bokeh at:          172.30.10.9:39646
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:38520
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO -              nanny at:          172.30.10.9:43260
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              bokeh at:          172.30.10.9:34407
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-1id3ciju
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-zmv89h7d
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:45647
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:45647
distributed.worker - INFO -              nanny at:          172.30.10.9:45884
distributed.worker - INFO -              bokeh at:          172.30.10.9:44234
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-wi3ltzto
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:33671
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:33671
distributed.worker - INFO -              nanny at:          172.30.10.9:40635
distributed.worker - INFO -              bokeh at:          172.30.10.9:42144
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-fho5fe2e
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:35196
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:35196
distributed.worker - INFO -              nanny at:          172.30.10.9:45443
distributed.worker - INFO -              bokeh at:          172.30.10.9:41918
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-0ve98f2u
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:35681
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:35681
distributed.worker - INFO -              nanny at:          172.30.10.9:43844
distributed.worker - INFO -              bokeh at:          172.30.10.9:41802
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-bygpwxoi
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:42283
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:42283
distributed.worker - INFO -              nanny at:          172.30.10.9:38745
distributed.worker - INFO -              bokeh at:          172.30.10.9:38948
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-0_vfc0us
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:42255
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:42255
distributed.worker - INFO -              nanny at:          172.30.10.9:34629
distributed.worker - INFO -              bokeh at:          172.30.10.9:34655
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-un1gex3e
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:37954
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:37954
distributed.worker - INFO -              nanny at:          172.30.10.9:40939
distributed.worker - INFO -              bokeh at:          172.30.10.9:44444
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-z4otq1d9
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:40393
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:40393
distributed.worker - INFO -              nanny at:          172.30.10.9:40603
distributed.worker - INFO -              bokeh at:          172.30.10.9:33419
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-nx2j_t6b
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:46253
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:46253
distributed.worker - INFO -              nanny at:          172.30.10.9:44863
distributed.worker - INFO -              bokeh at:          172.30.10.9:41283
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-lnz30xx4
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:33096
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:33096
distributed.worker - INFO -              nanny at:          172.30.10.9:35287
distributed.worker - INFO -              bokeh at:          172.30.10.9:43145
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-0zhxdaqn
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:46488
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:46488
distributed.worker - INFO -              nanny at:          172.30.10.9:40056
distributed.worker - INFO -              bokeh at:          172.30.10.9:44798
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-_m49ptql
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:42633
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:42633
distributed.worker - INFO -              nanny at:          172.30.10.9:46682
distributed.worker - INFO -              bokeh at:          172.30.10.9:34968
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-f9ldhzak
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:38260
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:38260
distributed.worker - INFO -              nanny at:          172.30.10.9:38414
distributed.worker - INFO -              bokeh at:          172.30.10.9:42980
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-6oijmwa9
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:45247
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:45247
distributed.worker - INFO -              nanny at:          172.30.10.9:34825
distributed.worker - INFO -              bokeh at:          172.30.10.9:37961
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-tkf9v2vr
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:38389
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:38389
distributed.worker - INFO -              nanny at:          172.30.10.9:39408
distributed.worker - INFO -              bokeh at:          172.30.10.9:34107
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-nlhyaywq
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:39345
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:39345
distributed.worker - INFO -              nanny at:          172.30.10.9:35551
distributed.worker - INFO -              bokeh at:          172.30.10.9:38109
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-pcfx7akw
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:37914
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:37914
distributed.worker - INFO -              nanny at:          172.30.10.9:44984
distributed.worker - INFO -              bokeh at:          172.30.10.9:34294
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-6vipr_cg
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:45293
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:45293
distributed.worker - INFO -              nanny at:          172.30.10.9:39011
distributed.worker - INFO -              bokeh at:          172.30.10.9:33057
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-dq0_ht5g
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:42180
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:42180
distributed.worker - INFO -              nanny at:          172.30.10.9:37497
distributed.worker - INFO -              bokeh at:          172.30.10.9:40349
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-phd8fmbc
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:37930
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:37930
distributed.worker - INFO -              nanny at:          172.30.10.9:33107
distributed.worker - INFO -              bokeh at:          172.30.10.9:39474
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-trc44hv1
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:35591
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:35591
distributed.worker - INFO -              nanny at:          172.30.10.9:32915
distributed.worker - INFO -              bokeh at:          172.30.10.9:46664
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-ik_356l3
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.10.9:38430
distributed.worker - INFO -          Listening to:    tcp://172.30.10.9:38430
distributed.worker - INFO -              nanny at:          172.30.10.9:39151
distributed.worker - INFO -              bokeh at:          172.30.10.9:43474
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-nzyvu4uw
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Event loop was unresponsive in Worker for 163.15s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 163.16s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 163.33s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 163.15s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6c61400>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[-6.4098112e-02, -6.4130828e-02, -6.4318523e-02, ...,
          -5.1778134e-02, -4.9837232e-02, -4.7934826e-02],
         [-6.4606771e-02, -6.4576156e-02, -6.4679772e-02, ...,
          -5.1228642e-02, -4.9305867e-02, -4.7405265e-02],
         [-6.5181442e-02, -6.5096192e-02, -6.5126240e-02, ...,
          -5.1183473e-02, -4.9332529e-02, -4.7505878e-02],
         ...,
         [-1.4244707e-01, -1.4596955e-01, -1.5023342e-01, ...,
          -1.5349166e-01, -1.5419252e-01, -1.5402223e-01],
         [-2.2227025e-23, -2.6932819e-23, -1.4542709e-23, ...,
          -3.6951681e-24, -1.0636869e-23,  1.5671846e-22],
         [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
           0.0000000e+00,  0.0000000e+00,  0.0000000e+00]]]],
      dtype=float32), array([[[[-4.6114326e-02, -4.4414550e-02, -4.2868827e-02, ...,
       
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6c17ea0>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[-0.09534021, -0.09592854, -0.096267  , ..., -0.18314163,
          -0.17885333, -0.17263645],
         [-0.10014094, -0.10076886, -0.10116725, ..., -0.18852201,
          -0.18281244, -0.17518586],
         [-0.10489564, -0.10558908, -0.10612771, ..., -0.191423  ,
          -0.18432024, -0.17538537],
         ...,
         [-0.2081191 , -0.20347276, -0.19793431, ..., -0.0669624 ,
          -0.08618132, -0.10543032],
         [-0.22672744, -0.22406341, -0.22032055, ..., -0.10257653,
          -0.11989881, -0.13501814],
         [-0.23959367, -0.23937818, -0.23808785, ..., -0.13531755,
          -0.14775696, -0.15697052]]]], dtype=float32), array([[[[-0.16441737, -0.15424758, -0.14221416, ..., -0.04593792,
          -0.03258295, -0.03292907],
         [-0.16564243, -0.15430593, -0.14131275, ..., -0.06961793,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6ce1730>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[ 0.06039871,  0.06949368,  0.07792904, ...,  0.17861266,
           0.17605296,  0.17320469],
         [ 0.04958846,  0.05886818,  0.0673058 , ...,  0.15390374,
           0.15192178,  0.14968626],
         [ 0.03668919,  0.04663796,  0.05552476, ...,  0.13269502,
           0.13114035,  0.12933287],
         ...,
         [-0.11173882, -0.11474694, -0.11724107, ..., -0.08581658,
          -0.07916632, -0.07256583],
         [-0.10050423, -0.10387139, -0.1066598 , ..., -0.07157484,
          -0.06492249, -0.05837544],
         [-0.0894443 , -0.09317993, -0.09628978, ..., -0.06001346,
          -0.05328526, -0.04670056]]]], dtype=float32), array([[[[ 0.1700462 ,  0.16654164,  0.1626563 , ..., -0.11291537,
          -0.13948536, -0.14451307],
         [ 0.14716002,  0.14428605,  0.14100134, ..., -0.14107464,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6c8c950>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[ 0.02831397,  0.03048425,  0.03253404, ...,  0.04856427,
           0.044525  ,  0.03182939],
         [ 0.02684711,  0.02891882,  0.03091953, ...,  0.04830847,
           0.04383201,  0.03153368],
         [ 0.02692777,  0.02896048,  0.03098561, ...,  0.04818079,
           0.04341113,  0.03174672],
         ...,
         [ 0.00842594,  0.00666619,  0.00468197, ..., -0.0248849 ,
          -0.0264337 , -0.02777784],
         [ 0.01084797,  0.00904258,  0.00694123, ..., -0.0313704 ,
          -0.03319693, -0.03476617],
         [ 0.01359967,  0.01196939,  0.00998195, ..., -0.03805306,
          -0.04009715, -0.04176335]]]], dtype=float32), array([[[[ 0.01629059,  0.00804617,  0.00786539, ..., -0.06033984,
          -0.05649244, -0.05341464],
         [ 0.01644737,  0.0075958 ,  0.00683744, ..., -0.05688938,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6c83c80>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[ 0.12168381,  0.12036   ,  0.11987317, ..., -0.01532646,
          -0.02030837, -0.02726053],
         [ 0.12266527,  0.12287773,  0.12387999, ..., -0.01567043,
          -0.02090635, -0.02819806],
         [ 0.12669463,  0.12833011,  0.13058941, ..., -0.01560402,
          -0.02100259, -0.02854556],
         ...,
         [ 0.04270331,  0.04307661,  0.04322524, ...,  0.05201627,
           0.05350996,  0.05453002],
         [ 0.0384677 ,  0.03891739,  0.03917382, ...,  0.05172665,
           0.05323489,  0.05422792],
         [ 0.03451991,  0.03505873,  0.0354414 , ...,  0.05128095,
           0.05281155,  0.05380031]]]], dtype=float32), array([[[[-0.03469114, -0.04169773, -0.04811938, ...,  0.05072482,
           0.05314589,  0.0568713 ],
         [-0.0360401 , -0.04349305, -0.05039179, ...,  0.05105649,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6c6f378>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[-0.00326604, -0.00367729, -0.00386057, ...,  0.15438963,
           0.15581211,  0.1569133 ],
         [ 0.00845511,  0.00942827,  0.01009097, ...,  0.16054201,
           0.16130742,  0.16168381],
         [ 0.01663176,  0.01918656,  0.02126318, ...,  0.16649719,
           0.16653603,  0.16605732],
         ...,
         [-0.14806704, -0.15267573, -0.1574789 , ..., -0.20864794,
          -0.2063973 , -0.20389646],
         [-0.1394536 , -0.14573474, -0.15240774, ..., -0.19507983,
          -0.19266815, -0.18996198],
         [-0.13095509, -0.13812487, -0.14564294, ..., -0.18244685,
          -0.18007472, -0.17738922]]]], dtype=float32), array([[[[ 0.15760009,  0.15774095,  0.15730289, ...,  0.02660532,
           0.04140294,  0.05095641],
         [ 0.16148   ,  0.16064395,  0.15928419, ...,  0.02042629,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6c6b2f0>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[-0.02901261, -0.02806048, -0.0270357 , ...,  0.02656006,
           0.02629958,  0.02607721],
         [-0.02924636, -0.02833754, -0.02730167, ...,  0.02557938,
           0.02531674,  0.0251062 ],
         [-0.02940418, -0.02854518, -0.02751685, ...,  0.02470353,
           0.02443627,  0.02423586],
         ...,
         [-0.07070217, -0.06635317, -0.06397022, ...,  0.01854116,
           0.01882319,  0.01854074],
         [-0.08036935, -0.07840752, -0.07634526, ..., -0.00176685,
          -0.00156431, -0.00139484],
         [ 0.        ,  0.        ,  0.        , ...,  0.        ,
           0.        ,  0.        ]]]], dtype=float32), array([[[[ 0.02597354,  0.0260535 ,  0.02634332, ...,  0.        ,
           0.        ,  0.        ],
         [ 0.02501962,  0.02511047,  0.02538737, ...,  0.        ,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6cb8840>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[-0.11376807, -0.09916544, -0.07845239, ...,  0.42055595,
           0.42836994,  0.43054694],
         [-0.11762819, -0.10533314, -0.08756849, ...,  0.42030352,
           0.42610916,  0.42674568],
         [-0.11956912, -0.10900839, -0.09405876, ...,  0.41919258,
           0.422835  ,  0.42245322],
         ...,
         [ 0.06016079,  0.0772494 ,  0.09515468, ...,  0.2669213 ,
           0.25974536,  0.25192317],
         [ 0.07134824,  0.08875234,  0.10702333, ...,  0.25166923,
           0.24445315,  0.2366387 ],
         [ 0.08274869,  0.10041256,  0.11902317, ...,  0.23704049,
           0.22963727,  0.22173199]]]], dtype=float32), array([[[[ 0.4311546 ,  0.43828744,  0.4566781 , ..., -0.156909  ,
          -0.18845086, -0.2129502 ],
         [ 0.4279948 ,  0.43749177,  0.4582539 , ..., -0.16530298,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6c79ae8>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[-0.00597208, -0.02195963, -0.03754692, ..., -0.00599032,
          -0.00970835, -0.01511899],
         [-0.0074116 , -0.0235423 , -0.03923352, ..., -0.00195541,
          -0.00563457, -0.01089381],
         [-0.00899675, -0.02504775, -0.0405941 , ...,  0.00190604,
          -0.00163359, -0.00672241],
         ...,
         [ 0.02688588,  0.03142641,  0.03628323, ...,  0.0648288 ,
           0.06925092,  0.07145406],
         [ 0.023906  ,  0.02829211,  0.03333962, ...,  0.06406302,
           0.06830513,  0.07047352],
         [ 0.02146718,  0.02549864,  0.03039543, ...,  0.06324515,
           0.06723747,  0.0693456 ]]]], dtype=float32), array([[[[-0.01963296, -0.01762897, -0.00900783, ..., -0.17493917,
          -0.17842706, -0.18016979],
         [-0.01535483, -0.01367645, -0.0053346 , ..., -0.17620672,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6c4b158>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[0.09105202, 0.08968486, 0.08638354, ..., 0.0284274 ,
          0.02756269, 0.0245885 ],
         [0.09315354, 0.09494177, 0.09345261, ..., 0.02690865,
          0.02852318, 0.0264846 ],
         [0.08662079, 0.09271653, 0.09531785, ..., 0.02406899,
          0.02880718, 0.02849761],
         ...,
         [0.1493238 , 0.16008157, 0.17054062, ..., 0.02530249,
          0.01880149, 0.01511927],
         [0.14398958, 0.15474862, 0.16530503, ..., 0.01697346,
          0.01092225, 0.00865421],
         [0.13803793, 0.14857611, 0.1589757 , ..., 0.01001064,
          0.00508461, 0.0037135 ]]]], dtype=float32), array([[[[ 0.02145512,  0.01892647,  0.0168539 , ...,  0.02088955,
           0.02104034,  0.02069398],
         [ 0.02332741,  0.02057763,  0.01835055, ...,  0.02451038,
           0.02451346,  0.02389809],
         [ 0
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6c4eae8>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[ 0.01523381,  0.01826494,  0.02123996, ..., -0.03194664,
          -0.03399212, -0.03458123],
         [ 0.02285607,  0.02575938,  0.02874358, ..., -0.03125032,
          -0.03313245, -0.03380769],
         [ 0.03097199,  0.03366515,  0.03649417, ..., -0.03022   ,
          -0.03203066, -0.03286971],
         ...,
         [ 0.07604774,  0.07437459,  0.07163682, ..., -0.01483483,
          -0.01355904, -0.01309886],
         [ 0.07383464,  0.07300382,  0.07109242, ..., -0.01557276,
          -0.01450589, -0.01417861],
         [ 0.07019652,  0.07026877,  0.06937069, ..., -0.01670104,
          -0.01579718, -0.0155678 ]]]], dtype=float32), array([[[[-0.03408914, -0.03342479, -0.03432185, ...,  0.07260633,
           0.07459603,  0.07576438],
         [-0.03359604, -0.03320323, -0.03424309, ...,  0.08429804,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6c79bf8>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[-0.04168226, -0.04187582, -0.04204367, ...,  0.01523148,
           0.01632374,  0.01714067],
         [-0.04165937, -0.04178048, -0.04190044, ...,  0.01471851,
           0.01565648,  0.01633998],
         [-0.04163045, -0.04167431, -0.04173061, ...,  0.01428478,
           0.01507684,  0.01564457],
         ...,
         [-0.0816175 , -0.07808033, -0.07601825, ...,  0.02637806,
           0.02668034,  0.02634978],
         [-0.08953959, -0.08735297, -0.08504213, ...,  0.00154374,
           0.00174234,  0.00189922],
         [ 0.        ,  0.        ,  0.        , ...,  0.        ,
           0.        ,  0.        ]]]], dtype=float32), array([[[[0.0177137 , 0.01810315, 0.01839202, ..., 0.        ,
          0.        , 0.        ],
         [0.01680983, 0.01712915, 0.01737599, ..., 0.        ,
          0.        , 0
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6c9ed90>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[-0.029723  , -0.0265818 , -0.02320458, ...,  0.02630418,
           0.02680142,  0.02724465],
         [-0.02587145, -0.02445845, -0.02149825, ...,  0.0282974 ,
           0.02858327,  0.02877888],
         [-0.01973201, -0.02067002, -0.01903745, ...,  0.02970012,
           0.02979617,  0.02974262],
         ...,
         [ 0.05524766,  0.04760096,  0.03882237, ..., -0.26366597,
          -0.26502025, -0.26412362],
         [ 0.05598149,  0.0474916 ,  0.03788394, ..., -0.26829812,
          -0.26833922, -0.26630983],
         [ 0.05635127,  0.04702441,  0.03659097, ..., -0.2716556 ,
          -0.27047336, -0.2674693 ]]]], dtype=float32), array([[[[ 0.02764084,  0.02792036,  0.02817708, ..., -0.20599489,
          -0.21753268, -0.22112696],
         [ 0.02896012,  0.02904237,  0.02906023, ..., -0.19195557,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6c25d90>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[-0.04094701, -0.04433502, -0.0490546 , ..., -0.11057658,
          -0.11652011, -0.12130126],
         [-0.03349498, -0.03699026, -0.04084348, ..., -0.10420499,
          -0.11100575, -0.11666221],
         [-0.02603531, -0.0298582 , -0.03400343, ..., -0.09708062,
          -0.10438194, -0.11062615],
         ...,
         [-0.01909583, -0.01500101, -0.01078   , ..., -0.07656559,
          -0.07879656, -0.08129594],
         [-0.02224171, -0.01834697, -0.01426086, ..., -0.07713125,
          -0.07945073, -0.08195834],
         [-0.02521296, -0.02141687, -0.0174017 , ..., -0.07707693,
          -0.07921205, -0.08151709]]]], dtype=float32), array([[[[-0.12425836, -0.12537251, -0.12528025, ...,  0.01546584,
           0.01344891,  0.01337152],
         [-0.12062583, -0.12314646, -0.12457643, ...,  0.0127675 ,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6c46620>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]]), array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]]), array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]])], [array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ...
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6c77a60>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]]), array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]]), array([[[[1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         ...,
         [1., 1., 0., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.]]]])], [array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ...
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6c770d0>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[-1.8360775e-02, -1.7374933e-02, -1.6339198e-02, ...,
          -6.6797612e-03, -2.2383416e-03,  2.3890215e-03],
         [-1.5398256e-02, -1.4358601e-02, -1.3298341e-02, ...,
          -2.4523186e-03,  1.9249409e-03,  5.3143268e-03],
         [-1.2933358e-02, -1.1854916e-02, -1.0784267e-02, ...,
          -1.3014706e-03,  4.7689091e-04,  7.1906870e-05],
         ...,
         [ 6.6213262e-01,  6.6126001e-01,  6.5978205e-01, ...,
           2.9705301e-01,  2.7983683e-01,  2.5955892e-01],
         [-9.9389153e-24, -1.6626476e-23,  2.8632738e-24, ...,
           8.9726183e-24,  5.2977961e-25,  5.2903909e-23],
         [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
           0.0000000e+00,  0.0000000e+00,  0.0000000e+00]]]],
      dtype=float32), array([[[[ 6.6572451e-03,  1.0164091e-02,  1.2741838e-02, ...,
       
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6cce0d0>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[ 0.16988596,  0.16889332,  0.16818987, ..., -0.00354822,
          -0.00786967, -0.01191874],
         [ 0.17693056,  0.17653523,  0.1763358 , ..., -0.00477006,
          -0.00925034, -0.01346499],
         [ 0.18516314,  0.18506877,  0.18503998, ..., -0.00593056,
          -0.01060342, -0.01503434],
         ...,
         [ 0.08123442,  0.0819431 ,  0.08263991, ...,  0.09035099,
           0.09293321,  0.09487179],
         [ 0.07800852,  0.07867646,  0.07934424, ...,  0.09029041,
           0.09279144,  0.094666  ],
         [ 0.0750468 ,  0.07566955,  0.0763163 , ...,  0.09031441,
           0.09269524,  0.09453363]]]], dtype=float32), array([[[[-0.01579995, -0.01972263, -0.02385922, ...,  0.0483571 ,
           0.04541583,  0.04300327],
         [-0.01752666, -0.02159515, -0.02579456, ...,  0.05132392,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6ca97b8>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[-0.09502957, -0.09549135, -0.09539689, ..., -0.08397746,
          -0.081715  , -0.07826065],
         [-0.10046697, -0.1013692 , -0.10159617, ..., -0.08476356,
          -0.08330932, -0.08063979],
         [-0.10634419, -0.10780686, -0.10851822, ..., -0.08495835,
          -0.08420731, -0.08244114],
         ...,
         [ 0.06018697,  0.06200884,  0.06363069, ...,  0.03162304,
           0.03010909,  0.0284376 ],
         [ 0.05762824,  0.05965391,  0.06140849, ...,  0.03608033,
           0.03476389,  0.03320067],
         [ 0.05583352,  0.05794604,  0.05971069, ...,  0.04053671,
           0.03940326,  0.03790244]]]], dtype=float32), array([[[[-0.07425147, -0.07033376, -0.06648141, ...,  0.17897937,
           0.18936087,  0.19924009],
         [-0.0770959 , -0.07347905, -0.07004835, ...,  0.164174  ,
           0.
kwargs:    {}
Exception: OSError("Timed out trying to connect to 'tcp://172.30.100.1:40264' after 3 s: connect() didn't finish in time")

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6d1ee18>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[-0.11618386, -0.11633246, -0.11657948, ..., -0.17493917,
          -0.17842706, -0.18016979],
         [-0.1208495 , -0.12094718, -0.12107573, ..., -0.17620672,
          -0.17816803, -0.17845121],
         [-0.12578546, -0.12582436, -0.12581119, ..., -0.17629412,
          -0.17678389, -0.17577796],
         ...,
         [-0.25262988, -0.25549945, -0.26450998, ..., -0.03237721,
          -0.03653657, -0.04085886],
         [-0.2511659 , -0.25385544, -0.26276118, ..., -0.03863343,
          -0.0430234 , -0.04742054],
         [-0.24962954, -0.2519537 , -0.26070943, ..., -0.04450394,
          -0.04904015, -0.05340774]]]], dtype=float32), array([[[[-0.18002905, -0.17804044, -0.17435955, ...,  0.07606258,
           0.06905909,  0.06222595],
         [-0.17705515, -0.17407806, -0.16965902, ...,  0.07451629,
           0.
kwargs:    {}
Exception: OSError("Timed out trying to connect to 'tcp://172.30.100.1:40264' after 3 s: connect() didn't finish in time")

distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.9:39102 remote=tcp://172.30.100.1:40264>
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6cc0158>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[-0.06467207, -0.06778044, -0.07123595, ..., -0.19068989,
          -0.19634897, -0.20067056],
         [-0.06389421, -0.06719632, -0.07085517, ..., -0.1918561 ,
          -0.19708906, -0.20123814],
         [-0.06314246, -0.06664591, -0.07051197, ..., -0.19294542,
          -0.19780518, -0.20188986],
         ...,
         [-0.14034928, -0.13933253, -0.13777235, ..., -0.04783563,
          -0.03410171, -0.02184096],
         [-0.14053005, -0.13926509, -0.1377348 , ..., -0.04081844,
          -0.02661588, -0.01409002],
         [-0.14090517, -0.1395227 , -0.13809454, ..., -0.03404485,
          -0.01937869, -0.00662465]]]], dtype=float32), array([[[[-0.20420387, -0.20766203, -0.21120799, ...,  0.09769408,
           0.09392235,  0.08853311],
         [-0.2049288 , -0.20869438, -0.21245101, ...,  0.08948105,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6c8cae8>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[ 0.07175209,  0.07526091,  0.07838328, ...,  0.02660532,
           0.04140294,  0.05095641],
         [ 0.07524767,  0.07880923,  0.08196328, ...,  0.02042629,
           0.03642411,  0.04580179],
         [ 0.07909335,  0.0826872 ,  0.08593529, ...,  0.01659461,
           0.03324544,  0.04128151],
         ...,
         [ 0.04956296,  0.05098601,  0.05322658, ...,  0.02860638,
          -0.0094317 , -0.05128947],
         [ 0.04702824,  0.04823772,  0.05004555, ...,  0.05487882,
           0.03662289, -0.01189439],
         [ 0.04384446,  0.04470726,  0.0460709 , ...,  0.06497348,
           0.06045386,  0.03896483]]]], dtype=float32), array([[[[ 0.05584564,  0.05163671,  0.0463644 , ...,  0.31449547,
           0.32526302,  0.36636728],
         [ 0.06052215,  0.05418299,  0.04460028, ...,  0.30852354,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6ca3ea0>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[-0.02886439, -0.02711649, -0.02542084, ..., -0.0041982 ,
          -0.00601394, -0.00733904],
         [-0.03382624, -0.03309032, -0.03218733, ..., -0.00034417,
          -0.00310543, -0.00483476],
         [-0.03979012, -0.04053961, -0.0408369 , ...,  0.00471837,
           0.00090239, -0.00162136],
         ...,
         [ 0.10940913,  0.11293902,  0.11632557, ...,  0.02998064,
           0.03154159,  0.03436891],
         [ 0.10067815,  0.10465704,  0.10861396, ...,  0.03086118,
           0.03213392,  0.03447886],
         [ 0.08869787,  0.09251985,  0.09675083, ...,  0.03235353,
           0.03357419,  0.03556566]]]], dtype=float32), array([[[[-0.00867845, -0.00976372, -0.01016787, ...,  0.01193931,
           0.01158771,  0.01056103],
         [-0.0063302 , -0.0077772 , -0.0086274 , ...,  0.01053783,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.9:39144 remote=tcp://172.30.100.1:40264>
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6c8c158>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]]), array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]]), array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]])], [array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ...
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b93a6c7bd08>, (<function concrete at 0x2b9327588a60>, [[[[array([[[[ 0.0540117 ,  0.06042922,  0.06760647, ...,  0.14262709,
           0.15976089,  0.1806101 ],
         [ 0.06255844,  0.06971413,  0.07761467, ...,  0.12585069,
           0.13514811,  0.13465126],
         [ 0.0710913 ,  0.07916271,  0.08783517, ...,  0.10926984,
           0.10315304,  0.08514307],
         ...,
         [ 0.09041037,  0.08944272,  0.08765797, ..., -0.03081898,
          -0.04920391, -0.0810626 ],
         [ 0.08816759,  0.08663621,  0.08433356, ..., -0.01871326,
          -0.02960615, -0.05145765],
         [ 0.08530434,  0.08345675,  0.08043128, ..., -0.00818842,
          -0.0171397 , -0.02458551]]]], dtype=float32), array([[[[ 0.17547992,  0.06848719, -0.00160804, ...,  0.10865875,
           0.12201275,  0.14071633],
         [ 0.1096327 ,  0.0112595 ,  0.00834793, ...,  0.09661284,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.9:39126 remote=tcp://172.30.100.1:40264>
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.9:39100 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.9:39106 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.9:39162 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.9:39196 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.9:39104 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.9:39068 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.9:39130 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.9:39242 remote=tcp://172.30.100.1:40264>
distributed.worker - ERROR - failed during get data with tcp://172.30.10.9:38389 -> tcp://172.30.10.9:37023
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/tcp.py", line 194, in read
    n_frames = yield stream.read_bytes(8)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 1114, in get_data
    response = yield comm.read(deserializers=serializers)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/tcp.py", line 214, in read
    convert_stream_closed_error(self, e)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/tcp.py", line 139, in convert_stream_closed_error
    raise CommClosedError("in %s: %s: %s" % (obj, exc.__class__.__name__, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: TimeoutError: [Errno 110] Connection timed out
distributed.core - INFO - Lost connection to 'tcp://172.30.10.9:50002': in <closed TCP>: TimeoutError: [Errno 110] Connection timed out
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.9:39098 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.9:39132 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.9:39240 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.9:39160 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.9:39226 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.9:39128 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.9:39134 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.9:39142 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.9:39170 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.9:39146 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.9:39230 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.9:39212 remote=tcp://172.30.100.1:40264>
slurmstepd: error: *** JOB 8988021 ON n2960 CANCELLED AT 2020-01-27T17:19:46 DUE TO TIME LIMIT ***
