/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:40522'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:41143'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:34238'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:45709'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:37626'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:34759'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:37339'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:39454'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:44919'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:37783'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:36225'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:35659'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:42845'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:33379'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:35090'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:33838'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:37885'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:43410'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:35976'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:35335'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:42559'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:40511'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:42992'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:39533'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:46436'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:34413'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:34395'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.131:39354'
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:40814
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:40814
distributed.worker - INFO -              nanny at:         172.30.8.131:36225
distributed.worker - INFO -              bokeh at:         172.30.8.131:33262
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-43cmdl88
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:42185
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:42185
distributed.worker - INFO -              nanny at:         172.30.8.131:37783
distributed.worker - INFO -              bokeh at:         172.30.8.131:33557
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-p45rlgdb
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:35493
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:35493
distributed.worker - INFO -              nanny at:         172.30.8.131:34413
distributed.worker - INFO -              bokeh at:         172.30.8.131:36905
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-jm_3c38b
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:35465
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:35465
distributed.worker - INFO -              nanny at:         172.30.8.131:42559
distributed.worker - INFO -              bokeh at:         172.30.8.131:41483
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-8jkt48j4
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:46481
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:46481
distributed.worker - INFO -              nanny at:         172.30.8.131:35090
distributed.worker - INFO -              bokeh at:         172.30.8.131:40517
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-rj1pyqb_
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:35771
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:35771
distributed.worker - INFO -              nanny at:         172.30.8.131:33838
distributed.worker - INFO -              bokeh at:         172.30.8.131:37994
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-1glq30kv
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:40161
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:40161
distributed.worker - INFO -              nanny at:         172.30.8.131:33379
distributed.worker - INFO -              bokeh at:         172.30.8.131:42340
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-_pal_6uu
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:42983
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:42983
distributed.worker - INFO -              nanny at:         172.30.8.131:37885
distributed.worker - INFO -              bokeh at:         172.30.8.131:33490
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-tsxqjb6b
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:39035
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:39035
distributed.worker - INFO -              nanny at:         172.30.8.131:34759
distributed.worker - INFO -              bokeh at:         172.30.8.131:40027
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-opb4s36_
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:42699
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:42699
distributed.worker - INFO -              nanny at:         172.30.8.131:46436
distributed.worker - INFO -              bokeh at:         172.30.8.131:44771
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-kf9kbbov
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:42896
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:42896
distributed.worker - INFO -              nanny at:         172.30.8.131:34238
distributed.worker - INFO -              bokeh at:         172.30.8.131:43334
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:35961
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:35961
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:         172.30.8.131:41143
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-gz1__ubx
distributed.worker - INFO -              bokeh at:         172.30.8.131:35606
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-7o303mrm
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:41847
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:41847
distributed.worker - INFO -              nanny at:         172.30.8.131:42992
distributed.worker - INFO -              bokeh at:         172.30.8.131:38970
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-vk9l_uco
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:37512
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:37512
distributed.worker - INFO -              nanny at:         172.30.8.131:35976
distributed.worker - INFO -              bokeh at:         172.30.8.131:38850
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-52u9d8mv
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:44340
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:44340
distributed.worker - INFO -              nanny at:         172.30.8.131:39354
distributed.worker - INFO -              bokeh at:         172.30.8.131:40059
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-x38axz9v
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:39559
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:39559
distributed.worker - INFO -              nanny at:         172.30.8.131:45709
distributed.worker - INFO -              bokeh at:         172.30.8.131:45143
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-75jf0qrs
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:45524
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:45524
distributed.worker - INFO -              nanny at:         172.30.8.131:39454
distributed.worker - INFO -              bokeh at:         172.30.8.131:39174
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-y_za2_gc
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:33894
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:33894
distributed.worker - INFO -              nanny at:         172.30.8.131:40522
distributed.worker - INFO -              bokeh at:         172.30.8.131:39841
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-gqqagjax
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:40184
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:40184
distributed.worker - INFO -              nanny at:         172.30.8.131:37339
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              bokeh at:         172.30.8.131:40716
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.core - INFO - Starting established connection
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.core - INFO - Starting established connection
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-nv4_qm40
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:39514
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:39514
distributed.worker - INFO -              nanny at:         172.30.8.131:40511
distributed.worker - INFO -              bokeh at:         172.30.8.131:41231
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-61o_px2n
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:35483
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:35483
distributed.worker - INFO -              nanny at:         172.30.8.131:37626
distributed.worker - INFO -              bokeh at:         172.30.8.131:45937
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-dvduzt0n
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:35255
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:35255
distributed.worker - INFO -              nanny at:         172.30.8.131:42845
distributed.worker - INFO -              bokeh at:         172.30.8.131:37664
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-_bi5g949
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:46080
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:46080
distributed.worker - INFO -              nanny at:         172.30.8.131:34395
distributed.worker - INFO -              bokeh at:         172.30.8.131:42659
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-hd6d_l2w
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:35738
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:35738
distributed.worker - INFO -              nanny at:         172.30.8.131:44919
distributed.worker - INFO -              bokeh at:         172.30.8.131:34902
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-oeloaqv2
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:46318
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:46318
distributed.worker - INFO -              nanny at:         172.30.8.131:35335
distributed.worker - INFO -              bokeh at:         172.30.8.131:35920
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-i36ruih6
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:40033
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:40033
distributed.worker - INFO -              nanny at:         172.30.8.131:39533
distributed.worker - INFO -              bokeh at:         172.30.8.131:39594
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-g76fju3c
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:33047
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:33047
distributed.worker - INFO -              nanny at:         172.30.8.131:35659
distributed.worker - INFO -              bokeh at:         172.30.8.131:42888
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-li5xkssg
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.131:35435
distributed.worker - INFO -          Listening to:   tcp://172.30.8.131:35435
distributed.worker - INFO -              nanny at:         172.30.8.131:43410
distributed.worker - INFO -              bokeh at:         172.30.8.131:40098
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-8ezge4hf
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Event loop was unresponsive in Worker for 163.15s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 163.16s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 163.15s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 163.15s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 163.16s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 163.34s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 163.35s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 163.16s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2abf1adee1e0>, (<function concrete at 0x2abe9b566a60>, [[[[array([[[[0.04859458, 0.05153632, 0.05449374, ..., 0.00570339,
          0.00387546, 0.00227696],
         [0.05725167, 0.06004092, 0.06264677, ..., 0.00676557,
          0.00485201, 0.00315338],
         [0.06619357, 0.0687347 , 0.07078569, ..., 0.00790847,
          0.0058923 , 0.00409106],
         ...,
         [0.09098754, 0.09115584, 0.09076929, ..., 0.01421664,
          0.01576078, 0.01645544],
         [0.08570746, 0.08696759, 0.08755091, ..., 0.01284871,
          0.01422044, 0.01482533],
         [0.07943839, 0.08154839, 0.08312365, ..., 0.01125397,
          0.01244329, 0.01297136]]]], dtype=float32), array([[[[ 0.00029389, -0.00293018, -0.00749189, ...,  0.10117704,
           0.10273892,  0.10304051],
         [ 0.00110605, -0.00215793, -0.00671967, ...,  0.11383013,
           0.11443603,  0.11372508],
         [ 0
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2abf1b0f6950>, (<function concrete at 0x2abe9b566a60>, [[[[array([[[[-0.04590677, -0.04091025, -0.03518497, ..., -0.06054311,
          -0.05996967, -0.05737711],
         [-0.05249441, -0.04781384, -0.04221169, ..., -0.06271551,
          -0.06166058, -0.05922293],
         [-0.05872714, -0.05475282, -0.04972965, ..., -0.06482342,
          -0.06353275, -0.06150969],
         ...,
         [-0.06884048, -0.07341707, -0.07847896, ..., -0.11221038,
          -0.09950794, -0.08689266],
         [-0.06766342, -0.07218694, -0.07725687, ..., -0.0985138 ,
          -0.0867272 , -0.07467011],
         [-0.06698588, -0.07132652, -0.0762844 , ..., -0.08651372,
          -0.07536785, -0.06407663]]]], dtype=float32), array([[[[-0.05441995, -0.05377818, -0.05705442, ...,  0.11266235,
           0.12439115,  0.13813096],
         [-0.05718231, -0.0578697 , -0.06227737, ...,  0.09635639,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2abf1ae07400>, (<function concrete at 0x2abe9b566a60>, [[[[array([[[[-0.09824527, -0.09205188, -0.08365135, ...,  0.37411287,
           0.38912818,  0.40255442],
         [-0.10311989, -0.09902649, -0.09252662, ...,  0.37187427,
           0.38675496,  0.4002599 ],
         [-0.10645014, -0.1044365 , -0.1000796 , ...,  0.36969948,
           0.3846555 ,  0.39851794],
         ...,
         [ 0.04394042,  0.0541827 ,  0.06497002, ...,  0.18801136,
           0.17838274,  0.16912721],
         [ 0.04819649,  0.05953464,  0.07134513, ...,  0.17770053,
           0.16821732,  0.15911691],
         [ 0.05199296,  0.06448579,  0.07736474, ...,  0.1678501 ,
           0.15851228,  0.1491347 ]]]], dtype=float32), array([[[[ 0.4138239 ,  0.42605942,  0.4428337 , ..., -0.24652691,
          -0.28089043, -0.3244631 ],
         [ 0.41228935,  0.42597377,  0.44417468, ..., -0.25337967,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2abf1ad6bc80>, (<function concrete at 0x2abe9b566a60>, [[[[array([[[[ 0.20544922,  0.20412582,  0.20423625, ...,  0.16732232,
           0.16418102,  0.16111186],
         [ 0.17105427,  0.1709309 ,  0.17513087, ...,  0.17396061,
           0.17175685,  0.16930653],
         [ 0.14492863,  0.15212995,  0.16151315, ...,  0.1791247 ,
           0.17763431,  0.17615478],
         ...,
         [ 0.10074749,  0.1005229 ,  0.09911278, ..., -0.02335921,
          -0.02705682, -0.02972836],
         [ 0.09977482,  0.10131734,  0.10129234, ..., -0.02133287,
          -0.02509123, -0.02818419],
         [ 0.09718475,  0.10085668,  0.10249149, ..., -0.02040197,
          -0.02372397, -0.02660577]]]], dtype=float32), array([[[[ 0.15832804,  0.1561901 ,  0.15437144, ..., -0.0417919 ,
          -0.04224754, -0.04263716],
         [ 0.16752379,  0.16725348,  0.16775107, ..., -0.04202574,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2abf1ae5f840>, (<function concrete at 0x2abe9b566a60>, [[[[array([[[[-5.9649065e-02, -5.9760172e-02, -5.9736948e-02, ...,
          -6.1733898e-02, -6.1220083e-02, -6.0807806e-02],
         [-5.9872147e-02, -6.0036197e-02, -6.0048822e-02, ...,
          -6.0977623e-02, -6.0207359e-02, -5.9601158e-02],
         [-6.0036685e-02, -6.0256690e-02, -6.0315199e-02, ...,
          -6.0584079e-02, -5.9549812e-02, -5.8687538e-02],
         ...,
         [ 1.3208568e-01,  1.2661833e-01,  1.2103635e-01, ...,
           8.9516528e-02,  8.6294770e-02,  8.3460949e-02],
         [-1.2050711e-23, -3.8230897e-24, -2.9324358e-24, ...,
          -7.0742861e-24, -1.3839381e-23, -4.5066226e-23],
         [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
           0.0000000e+00,  0.0000000e+00,  0.0000000e+00]]]],
      dtype=float32), array([[[[-6.0374886e-02, -5.9788685e-02, -5.8951180e-02, ...,
       
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2abf1b14d620>, (<function concrete at 0x2abe9b566a60>, [[[[array([[[[-0.03788186, -0.03380015, -0.03064487, ..., -0.11206464,
          -0.11095405, -0.10368607],
         [-0.04492304, -0.04149054, -0.03854028, ..., -0.12051525,
          -0.11652382, -0.10778762],
         [-0.0508647 , -0.04819528, -0.04562364, ..., -0.1274354 ,
          -0.1209952 , -0.11130263],
         ...,
         [-0.1504503 , -0.16167466, -0.17356037, ..., -0.22997761,
          -0.21194875, -0.19330329],
         [-0.15361373, -0.16499588, -0.17718561, ..., -0.21447942,
          -0.19613183, -0.17735659],
         [-0.15617244, -0.16759568, -0.17999639, ..., -0.19744328,
          -0.17882113, -0.15971313]]]], dtype=float32), array([[[[-0.09497905, -0.089376  , -0.08920408, ...,  0.07968152,
           0.09528386,  0.10596547],
         [-0.09902401, -0.09420893, -0.09500334, ...,  0.06429149,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2abf1ae926a8>, (<function concrete at 0x2abe9b566a60>, [[[[array([[[[ 0.01180719,  0.01012006,  0.00838926, ..., -0.14076181,
          -0.1379757 , -0.13523845],
         [ 0.01000855,  0.00834858,  0.00664651, ..., -0.13799961,
          -0.13399556, -0.13023333],
         [ 0.00845478,  0.00677148,  0.00501169, ..., -0.13423364,
          -0.12917973, -0.12460174],
         ...,
         [-0.05145126, -0.05166053, -0.05185067, ..., -0.01970402,
          -0.01662829, -0.0135053 ],
         [-0.05211706, -0.05213799, -0.05215621, ..., -0.01587569,
          -0.01284481, -0.00966567],
         [-0.05311737, -0.05290404, -0.05267918, ..., -0.01174026,
          -0.00866843, -0.00532204]]]], dtype=float32), array([[[[-0.13319899, -0.13253652, -0.13390516, ..., -0.23076689,
          -0.23490389, -0.24423495],
         [-0.12736407, -0.12603188, -0.12691088, ..., -0.22611572,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2abf1b1ad048>, (<function concrete at 0x2abe9b566a60>, [[[[array([[[[-7.2767563e-02, -7.2715305e-02, -7.2648294e-02, ...,
          -7.5091764e-02, -7.4439414e-02, -7.3573641e-02],
         [-7.3078431e-02, -7.3047943e-02, -7.2994724e-02, ...,
          -7.3956765e-02, -7.3257878e-02, -7.2454229e-02],
         [-7.3384494e-02, -7.3383816e-02, -7.3352933e-02, ...,
          -7.3063582e-02, -7.2204620e-02, -7.1353376e-02],
         ...,
         [ 6.5641895e-02,  5.8115885e-02,  5.1013555e-02, ...,
           4.2169791e-02,  3.9754879e-02,  3.7674267e-02],
         [-1.8879691e-23, -1.7700166e-23, -1.3750661e-23, ...,
          -1.4164608e-23, -1.2420288e-23, -1.1102581e-22],
         [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
           0.0000000e+00,  0.0000000e+00,  0.0000000e+00]]]],
      dtype=float32), array([[[[-7.2449841e-02, -7.1082041e-02, -6.9532089e-02, ...,
       
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2abf1aec0620>, (<function concrete at 0x2abe9b566a60>, [[[[array([[[[-0.17158702, -0.17330945, -0.17395066, ..., -0.10264321,
          -0.09889743, -0.0953783 ],
         [-0.1752769 , -0.17794017, -0.17952175, ..., -0.10273642,
          -0.09896384, -0.09558366],
         [-0.17677504, -0.18034771, -0.1829064 , ..., -0.10263664,
          -0.09886844, -0.0956587 ],
         ...,
         [ 0.04336686,  0.04607737,  0.04836043, ...,  0.03399288,
           0.03193314,  0.02911479],
         [ 0.04333892,  0.04606833,  0.04816823, ...,  0.03860581,
           0.03656368,  0.0335607 ],
         [ 0.04335423,  0.04570748,  0.04732021, ...,  0.04316309,
           0.040992  ,  0.03768541]]]], dtype=float32), array([[[[-0.09196923, -0.08884338, -0.08609066, ...,  0.2298595 ,
           0.23807877,  0.24550074],
         [-0.09236508, -0.08939363, -0.08691185, ...,  0.21839999,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2abf1ad438c8>, (<function concrete at 0x2abe9b566a60>, [[[[array([[[[-5.08227609e-02, -5.11127599e-02, -5.12320548e-02, ...,
          -5.89864552e-02, -5.82210571e-02, -5.76789826e-02],
         [-5.09320833e-02, -5.12842909e-02, -5.14583290e-02, ...,
          -5.86979985e-02, -5.76892234e-02, -5.68639487e-02],
         [-5.10132201e-02, -5.14308065e-02, -5.16687818e-02, ...,
          -5.85851297e-02, -5.74232154e-02, -5.63599169e-02],
         ...,
         [ 1.55469596e-01,  1.51227668e-01,  1.46433622e-01, ...,
           9.93507206e-02,  9.57661197e-02,  9.25763175e-02],
         [-3.65401831e-24, -7.27266961e-24, -7.41892127e-24, ...,
          -1.43024584e-23, -1.11838696e-23,  2.40497664e-22],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00]]]],
      dtype=float32), array([[[[-5.7326686e-02, -5.70724
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2abf1ad5fe18>, (<function concrete at 0x2abe9b566a60>, [[[[array([[[[ 0.02460732,  0.01021783, -0.00520615, ..., -0.24652691,
          -0.28089043, -0.3244631 ],
         [ 0.02154603,  0.00700812, -0.00866877, ..., -0.25337967,
          -0.2879559 , -0.3340902 ],
         [ 0.01814265,  0.00360951, -0.01217388, ..., -0.2612625 ,
          -0.29804504, -0.34259024],
         ...,
         [-0.10112626, -0.10164328, -0.10199203, ..., -0.09345507,
          -0.11001348, -0.13382989],
         [-0.10059261, -0.10078354, -0.10070013, ..., -0.08007461,
          -0.09085474, -0.10208906],
         [-0.10002305, -0.09978731, -0.09929535, ..., -0.06624531,
          -0.07768732, -0.08820136]]]], dtype=float32), array([[[[-0.36537218, -0.12113795,  0.03359167, ...,  0.11279391,
           0.1199481 ,  0.12437931],
         [-0.36949986, -0.07745057,  0.0389746 , ...,  0.10552771,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2abf1ad40ea0>, (<function concrete at 0x2abe9b566a60>, [[[[array([[[[-0.01564799, -0.01213192, -0.01290113, ...,  0.13291167,
           0.14516388,  0.1564522 ],
         [-0.01640758, -0.01297961, -0.0139874 , ...,  0.11866855,
           0.13134052,  0.14360733],
         [-0.01715025, -0.01399999, -0.01539063, ...,  0.10538052,
           0.11691316,  0.12868018],
         ...,
         [ 0.13171452,  0.13580422,  0.13898419, ...,  0.01511571,
           0.01319747,  0.01007492],
         [ 0.13248658,  0.13747634,  0.14152779, ...,  0.02053072,
           0.02046608,  0.01839122],
         [ 0.13114925,  0.1370728 ,  0.14199947, ...,  0.02474711,
           0.02583635,  0.02548505]]]], dtype=float32), array([[[[0.16645728, 0.17502089, 0.18212414, ..., 0.01522415,
          0.01453107, 0.01440202],
         [0.1551089 , 0.16553402, 0.17463562, ..., 0.01636918,
          0.01532031, 0
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2abf1bab78c8>, (<function concrete at 0x2abe9b566a60>, [[[[array([[[[-0.06232715, -0.06077022, -0.06004141, ..., -0.05617617,
          -0.07221847, -0.07954407],
         [-0.06441058, -0.06290901, -0.06229273, ..., -0.0779626 ,
          -0.08629284, -0.09176883],
         [-0.0655553 , -0.0643534 , -0.06388652, ..., -0.12423388,
          -0.1365568 , -0.16394661],
         ...,
         [-0.06396861, -0.06285755, -0.06122098, ...,  0.03776842,
           0.04312022,  0.04073886],
         [-0.06214633, -0.06075715, -0.058943  , ...,  0.00196472,
           0.00297576, -0.00456516],
         [-0.06011645, -0.05855552, -0.05665467, ..., -0.07493023,
          -0.08986139, -0.08931901]]]], dtype=float32), array([[[[-0.07156719, -0.0694979 , -0.07700888, ..., -0.04948642,
          -0.04381572, -0.03519766],
         [-0.08965494, -0.08141112, -0.08593771, ..., -0.05468628,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2abf1bc54158>, (<function concrete at 0x2abe9b566a60>, [[[[array([[[[-0.04342915, -0.03854739, -0.03426048, ...,  0.07997036,
           0.08117733,  0.08267073],
         [-0.04816998, -0.04355032, -0.03953354, ...,  0.08208766,
           0.08325784,  0.08471137],
         [-0.05208027, -0.0476627 , -0.0438656 , ...,  0.08400264,
           0.08512522,  0.08652383],
         ...,
         [ 0.09422927,  0.08564088,  0.07691394, ..., -0.00745572,
          -0.01018706, -0.01308547],
         [ 0.09689743,  0.08766168,  0.0783629 , ..., -0.0117723 ,
          -0.01514044, -0.01906141],
         [ 0.09950772,  0.08974163,  0.07994668, ..., -0.01651089,
          -0.02126673, -0.02676589]]]], dtype=float32), array([[[[ 0.0844776 ,  0.08660445,  0.08905715, ...,  0.21609561,
           0.21742478,  0.21280126],
         [ 0.08646438,  0.08852632,  0.09092168, ...,  0.21877006,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2abf1bb11d08>, (<function concrete at 0x2abe9b566a60>, [[[[array([[[[-0.0712476 , -0.07019455, -0.06886037, ...,  0.000237  ,
           0.00086655,  0.0017056 ],
         [-0.07012586, -0.06902028, -0.06766743, ...,  0.00154081,
           0.0035663 ,  0.00639923],
         [-0.06897859, -0.06780459, -0.06643999, ...,  0.00481182,
           0.00940416,  0.01429161],
         ...,
         [-0.0170706 , -0.01704498, -0.01819636, ...,  0.04116756,
           0.04747502,  0.0498656 ],
         [-0.05897212, -0.05753481, -0.0560526 , ..., -0.00949155,
          -0.00927981, -0.00908098],
         [ 0.        ,  0.        ,  0.        , ...,  0.        ,
           0.        ,  0.        ]]]], dtype=float32), array([[[[ 0.00298753,  0.00464707,  0.00635911, ...,  0.        ,
           0.        ,  0.        ],
         [ 0.00965871,  0.01262047,  0.01452647, ...,  0.        ,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2abf1bad8730>, (<function concrete at 0x2abe9b566a60>, [[[[array([[[[-0.1457453 , -0.14543194, -0.14590369, ..., -0.06895196,
          -0.05736934, -0.04282998],
         [-0.14563388, -0.14511281, -0.14579055, ..., -0.07720586,
          -0.06648622, -0.0522812 ],
         [-0.14520635, -0.14465639, -0.14563878, ..., -0.08473495,
          -0.0752197 , -0.06172074],
         ...,
         [-0.17955473, -0.18597797, -0.19383901, ..., -0.04945305,
          -0.04634722, -0.04176648],
         [-0.18369465, -0.19066311, -0.19929686, ..., -0.05523729,
          -0.05235725, -0.0478668 ],
         [-0.1875069 , -0.19508508, -0.20451988, ..., -0.06153532,
          -0.05891148, -0.05478308]]]], dtype=float32), array([[[[-0.02590366, -0.0074955 ,  0.01154178, ...,  0.11937706,
           0.11510482,  0.11058822],
         [-0.03504634, -0.01578151,  0.00439584, ...,  0.11545941,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2abf1b20dae8>, (<function concrete at 0x2abe9b566a60>, [[[[array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]]), array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]]), array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]])], [array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ...
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2abf1ad23158>, (<function concrete at 0x2abe9b566a60>, [[[[array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]]], dtype=float32), array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]]], dtype=float32), array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]]], dtype=float32)], [array([[[[0.        
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.131:55070 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.131:55046 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.131:55048 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.131:55136 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.131:55132 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.131:55202 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.131:55190 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.131:55082 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.131:55166 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.131:55100 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.131:55084 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.131:55052 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.131:55054 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.131:55050 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.131:55014 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.131:55012 remote=tcp://172.30.100.1:40264>
slurmstepd: error: *** JOB 8988028 ON n2570 CANCELLED AT 2020-01-27T17:19:46 DUE TO TIME LIMIT ***
