/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:43088'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:34939'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:36138'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:37533'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:34975'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:46629'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:39011'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:36105'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:46699'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:43624'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:43104'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:40631'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:43628'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:36931'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:34012'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:41974'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:36344'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:46225'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:39717'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:35483'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:34565'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:34669'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:39171'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:43389'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:34358'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:33940'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:38734'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.170:44910'
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:33417
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:33417
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:37621
distributed.worker - INFO -              nanny at:         172.30.6.170:43624
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:37621
distributed.worker - INFO -              bokeh at:         172.30.6.170:33482
distributed.worker - INFO -              nanny at:         172.30.6.170:34565
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO -              bokeh at:         172.30.6.170:38875
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-j2tz359w
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-v6yv9ce5
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:36334
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:36334
distributed.worker - INFO -              nanny at:         172.30.6.170:34358
distributed.worker - INFO -              bokeh at:         172.30.6.170:46494
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-6wysydm_
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:40210
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:35294
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:40210
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:35294
distributed.worker - INFO -              nanny at:         172.30.6.170:34012
distributed.worker - INFO -              nanny at:         172.30.6.170:46225
distributed.worker - INFO -              bokeh at:         172.30.6.170:33109
distributed.worker - INFO -              bokeh at:         172.30.6.170:38076
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-s1lnkbk8
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-qhiqwopg
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:39746
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:41792
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:39746
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:41792
distributed.worker - INFO -              nanny at:         172.30.6.170:40631
distributed.worker - INFO -              nanny at:         172.30.6.170:43088
distributed.worker - INFO -              bokeh at:         172.30.6.170:37534
distributed.worker - INFO -              bokeh at:         172.30.6.170:45611
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-1krrika1
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-f5is86b6
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:38421
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:38421
distributed.worker - INFO -              nanny at:         172.30.6.170:34975
distributed.worker - INFO -              bokeh at:         172.30.6.170:34831
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-o0qqasjv
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:34860
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:34860
distributed.worker - INFO -              nanny at:         172.30.6.170:39717
distributed.worker - INFO -              bokeh at:         172.30.6.170:41934
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-pz0k9t3e
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:34564
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:34564
distributed.worker - INFO -              nanny at:         172.30.6.170:38734
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:36562
distributed.worker - INFO -              bokeh at:         172.30.6.170:39179
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:36562
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:         172.30.6.170:46699
distributed.worker - INFO -              bokeh at:         172.30.6.170:42930
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-8uq58syt
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-_v6i25hw
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:38284
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:38284
distributed.worker - INFO -              nanny at:         172.30.6.170:34939
distributed.worker - INFO -              bokeh at:         172.30.6.170:35320
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-ny1t9v0s
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:33807
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:33807
distributed.worker - INFO -              nanny at:         172.30.6.170:33940
distributed.worker - INFO -              bokeh at:         172.30.6.170:46188
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-h25vfnad
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:41049
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:41049
distributed.worker - INFO -              nanny at:         172.30.6.170:36105
distributed.worker - INFO -              bokeh at:         172.30.6.170:37319
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-jxvrakr2
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:38749
distributed.core - INFO - Starting established connection
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:38749
distributed.worker - INFO -              nanny at:         172.30.6.170:39011
distributed.worker - INFO -              bokeh at:         172.30.6.170:39378
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:45517
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-p150mk59
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:45517
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:43228
distributed.worker - INFO -              nanny at:         172.30.6.170:43628
distributed.worker - INFO -              bokeh at:         172.30.6.170:39233
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:43228
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:         172.30.6.170:41974
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -              bokeh at:         172.30.6.170:37331
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-bq07kmwz
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-lhz0toqj
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:45858
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:45858
distributed.worker - INFO -              nanny at:         172.30.6.170:46629
distributed.worker - INFO -              bokeh at:         172.30.6.170:39576
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-uofzcvmo
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:34168
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:34168
distributed.worker - INFO -              nanny at:         172.30.6.170:43389
distributed.worker - INFO -              bokeh at:         172.30.6.170:39752
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-kkzl1iyf
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:45662
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:45662
distributed.worker - INFO -              nanny at:         172.30.6.170:43104
distributed.worker - INFO -              bokeh at:         172.30.6.170:33897
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-pusx4k3i
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:35572
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:35572
distributed.worker - INFO -              nanny at:         172.30.6.170:34669
distributed.worker - INFO -              bokeh at:         172.30.6.170:41521
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-_ug531p5
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:41014
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:41014
distributed.worker - INFO -              nanny at:         172.30.6.170:36138
distributed.worker - INFO -              bokeh at:         172.30.6.170:45006
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-yak46pf3
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:37664
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:37664
distributed.worker - INFO -              nanny at:         172.30.6.170:35483
distributed.worker - INFO -              bokeh at:         172.30.6.170:38232
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-o2kf9xth
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:33029
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:33029
distributed.worker - INFO -              nanny at:         172.30.6.170:37533
distributed.worker - INFO -              bokeh at:         172.30.6.170:39384
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-tltlrvmc
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:41914
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:41914
distributed.worker - INFO -              nanny at:         172.30.6.170:39171
distributed.worker - INFO -              bokeh at:         172.30.6.170:42539
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-ugiqga_a
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:41580
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:41580
distributed.worker - INFO -              nanny at:         172.30.6.170:36344
distributed.worker - INFO -              bokeh at:         172.30.6.170:36952
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-29_kzcbt
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:40059
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:40059
distributed.worker - INFO -              nanny at:         172.30.6.170:36931
distributed.worker - INFO -              bokeh at:         172.30.6.170:42258
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-qk9mfxih
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.170:43836
distributed.worker - INFO -          Listening to:   tcp://172.30.6.170:43836
distributed.worker - INFO -              nanny at:         172.30.6.170:44910
distributed.worker - INFO -              bokeh at:         172.30.6.170:34417
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-cmjodnxp
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Event loop was unresponsive in Worker for 163.16s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 163.17s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 162.65s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 163.16s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b6c0bb6a730>, (<function concrete at 0x2b6b8be2ea60>, [[[[array([[[[-0.08587798, -0.09027448, -0.09520344, ..., -0.05727748,
          -0.05503126, -0.05357838],
         [-0.0868766 , -0.09097305, -0.09554139, ..., -0.05839385,
          -0.05579488, -0.05394822],
         [-0.08816634, -0.09193918, -0.09609254, ..., -0.05994721,
          -0.05709474, -0.05485128],
         ...,
         [-0.05092374, -0.03832353, -0.02695265, ...,  0.03155689,
           0.03081895,  0.02982428],
         [-0.0641991 , -0.04954871, -0.03605768, ...,  0.03536593,
           0.03362865,  0.03161438],
         [-0.07996901, -0.06365803, -0.0483088 , ...,  0.03799788,
           0.03528903,  0.0322712 ]]]], dtype=float32), array([[[[-0.05226738, -0.05071565, -0.04885549, ...,  0.05480079,
           0.04830868,  0.04875205],
         [-0.05233578, -0.05057744, -0.04849771, ...,  0.0759612 ,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b6c28167048>, (<function concrete at 0x2b6b8be2ea60>, [[[[array([[[[0.06511927, 0.07643251, 0.08324904, ..., 0.00968775,
          0.00703281, 0.00581264],
         [0.05796665, 0.06889902, 0.076254  , ..., 0.01717059,
          0.01427081, 0.01118748],
         [0.05335343, 0.06447355, 0.07181776, ..., 0.0242549 ,
          0.022049  , 0.01814038],
         ...,
         [0.08154234, 0.07890289, 0.07600583, ..., 0.02486199,
          0.02395165, 0.02323945],
         [0.08109047, 0.07856934, 0.07568889, ..., 0.02713391,
          0.02584124, 0.02468609],
         [0.07929249, 0.07701164, 0.07439191, ..., 0.02908719,
          0.02760817, 0.02622369]]]], dtype=float32), array([[[[ 0.00708435,  0.00962598,  0.01217256, ...,  0.01789335,
           0.01809255,  0.01705756],
         [ 0.01023454,  0.01152721,  0.01347756, ...,  0.01781318,
           0.019421  ,  0.01930274],
         [ 0
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b6c0b982950>, (<function concrete at 0x2b6b8be2ea60>, [[[[array([[[[-0.07375734, -0.07282437, -0.07172246, ..., -0.00465267,
          -0.0037683 , -0.00317622],
         [-0.07314549, -0.07201453, -0.07078587, ..., -0.00455248,
          -0.00337443, -0.00209946],
         [-0.07270629, -0.07137661, -0.0699706 , ..., -0.00449157,
          -0.00246904,  0.00059359],
         ...,
         [-0.03745608, -0.03852026, -0.04046513, ...,  0.015487  ,
           0.00538025, -0.00212147],
         [-0.06202887, -0.06051663, -0.05895155, ..., -0.00838802,
          -0.00817759, -0.00798296],
         [ 0.        ,  0.        ,  0.        , ...,  0.        ,
           0.        ,  0.        ]]]], dtype=float32), array([[[[-0.00265228, -0.00184389, -0.00053773, ...,  0.        ,
           0.        ,  0.        ],
         [-0.00023129,  0.00255705,  0.00605282, ...,  0.        ,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b6c0b666bf8>, (<function concrete at 0x2b6b8be2ea60>, [[[[array([[[[-4.8599169e-02, -4.9159393e-02, -4.9543951e-02, ...,
          -2.0229709e-03,  6.1737213e-05,  1.9512945e-03],
         [-4.8791558e-02, -4.9287725e-02, -4.9632475e-02, ...,
          -2.1468264e-03, -2.4970580e-04,  1.4704594e-03],
         [-4.9007349e-02, -4.9428668e-02, -4.9724758e-02, ...,
          -2.0882946e-03, -3.5849289e-04,  1.1934517e-03],
         ...,
         [-9.6712537e-02, -9.4655417e-02, -9.3867548e-02, ...,
           1.5991287e-02,  1.5994266e-02,  1.5243120e-02],
         [-9.2798844e-02, -9.0546206e-02, -8.8161290e-02, ...,
           1.5552950e-03,  1.7251648e-03,  1.8512253e-03],
         [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
           0.0000000e+00,  0.0000000e+00,  0.0000000e+00]]]],
      dtype=float32), array([[[[ 3.6311541e-03,  5.0905901e-03,  6.3265562e-03, ...,
       
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b6c0b9c30d0>, (<function concrete at 0x2b6b8be2ea60>, [[[[array([[[[-0.01696128, -0.01801779, -0.01933206, ..., -0.15724286,
          -0.15602404, -0.15365402],
         [-0.01933137, -0.02054878, -0.02195515, ..., -0.15223758,
          -0.15036838, -0.14755505],
         [-0.02196832, -0.02332098, -0.02478701, ..., -0.14701192,
          -0.14458257, -0.14144236],
         ...,
         [-0.05393438, -0.05449924, -0.0551758 , ..., -0.02007294,
          -0.01491366, -0.00911167],
         [-0.05227805, -0.05257684, -0.05295523, ..., -0.01786611,
          -0.01302266, -0.00762115],
         [-0.05088693, -0.05094265, -0.05105352, ..., -0.0154924 ,
          -0.01101732, -0.00609239]]]], dtype=float32), array([[[[-0.15321372, -0.15459786, -0.15443856, ..., -0.2813886 ,
          -0.28399622, -0.286414  ],
         [-0.14681402, -0.14853087, -0.1496333 , ..., -0.28317896,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b6c0b97d268>, (<function concrete at 0x2b6b8be2ea60>, [[[[array([[[[ 0.0006137 , -0.00100229, -0.00263293, ..., -0.16166067,
          -0.15232025, -0.14349593],
         [-0.00124324, -0.00277442, -0.00432647, ..., -0.15344363,
          -0.14381719, -0.13546123],
         [-0.00275286, -0.00422699, -0.00578132, ..., -0.14514068,
          -0.13557592, -0.12781638],
         ...,
         [-0.05950248, -0.05946651, -0.05914637, ..., -0.01738023,
          -0.01401514, -0.01059327],
         [-0.0606512 , -0.06074408, -0.0605413 , ..., -0.01371442,
          -0.01046887, -0.00705821],
         [-0.06144217, -0.06168782, -0.06166723, ..., -0.00978364,
          -0.00647252, -0.00289713]]]], dtype=float32), array([[[[-0.13721554, -0.13388738, -0.13191836, ..., -0.2302055 ,
          -0.23225066, -0.23218575],
         [-0.12998451, -0.12734099, -0.12577428, ..., -0.23294497,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b6c0b61bf28>, (<function concrete at 0x2b6b8be2ea60>, [[[[array([[[[-0.0662039 , -0.06654691, -0.06647635, ...,  0.14311837,
           0.14384267,  0.14454809],
         [-0.05464299, -0.05490559, -0.0546425 , ...,  0.1445952 ,
           0.14534792,  0.14622207],
         [-0.04247324, -0.04276251, -0.04245476, ...,  0.14674631,
           0.14777987,  0.14897993],
         ...,
         [-0.15329807, -0.15535109, -0.15726331, ..., -0.2538256 ,
          -0.25086898, -0.24684435],
         [-0.15547344, -0.1566113 , -0.1572594 , ..., -0.2439897 ,
          -0.24089386, -0.23674804],
         [-0.15608874, -0.15734209, -0.15746613, ..., -0.23001097,
          -0.22702594, -0.22308488]]]], dtype=float32), array([[[[ 0.14534634,  0.14629667,  0.14742234, ..., -0.03770422,
          -0.02069775, -0.00238259],
         [ 0.14725977,  0.14847556,  0.14986303, ..., -0.03404651,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b6c0ba408c8>, (<function concrete at 0x2b6b8be2ea60>, [[[[array([[[[-0.10614454, -0.1172575 , -0.11536083, ...,  0.07386237,
           0.09079354,  0.12237515],
         [-0.10857218, -0.11857797, -0.1141729 , ...,  0.08051246,
           0.11750919,  0.16306081],
         [-0.11071633, -0.11928327, -0.11201234, ...,  0.1278123 ,
           0.18545341,  0.2308778 ],
         ...,
         [ 0.08820377,  0.08536545,  0.0816763 , ...,  0.09451257,
           0.05378981,  0.02774251],
         [ 0.09059146,  0.08751243,  0.08351122, ...,  0.11859351,
           0.07979947,  0.04072278],
         [ 0.09259603,  0.08933243,  0.08508039, ...,  0.13947834,
           0.09506777,  0.0478413 ]]]], dtype=float32), array([[[[ 0.16047528,  0.20145634,  0.24142097, ..., -0.08182491,
          -0.08361546, -0.08316071],
         [ 0.1966379 ,  0.19757128,  0.23907103, ..., -0.08097932,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b6c0b71e488>, (<function concrete at 0x2b6b8be2ea60>, [[[[array([[[[-0.1186887 , -0.12376198, -0.12988293, ...,  0.01398322,
           0.02640644,  0.03966414],
         [-0.1217715 , -0.12630986, -0.13208911, ...,  0.00531903,
           0.01815645,  0.03198794],
         [-0.12426221, -0.12827854, -0.13374726, ..., -0.00368717,
           0.00953025,  0.02382243],
         ...,
         [-0.1301269 , -0.13844262, -0.1463168 , ..., -0.02748423,
          -0.02787209, -0.02743275],
         [-0.13276504, -0.14154723, -0.14977586, ..., -0.03344044,
          -0.03443614, -0.03416914],
         [-0.13563965, -0.1448736 , -0.15345454, ..., -0.03955932,
          -0.0408104 , -0.04054381]]]], dtype=float32), array([[[[ 0.05349147,  0.06754861,  0.08150849, ...,  0.11393894,
           0.1082045 ,  0.10190906],
         [ 0.046636  ,  0.06183816,  0.07724555, ...,  0.10866774,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b6c0b6277b8>, (<function concrete at 0x2b6b8be2ea60>, [[[[array([[[[-0.02719554, -0.02608313, -0.02525114, ...,  0.28164205,
           0.30353934,  0.32951507],
         [-0.02380547, -0.02216185, -0.02090187, ...,  0.28022954,
           0.30231476,  0.328164  ],
         [-0.02068789, -0.01852932, -0.01686102, ...,  0.27914232,
           0.301311  ,  0.32681578],
         ...,
         [-0.06391937, -0.04985584, -0.03707376, ...,  0.05493449,
           0.05098525,  0.04760522],
         [-0.07890685, -0.06187216, -0.04688766, ...,  0.0566581 ,
           0.05307557,  0.05016702],
         [-0.09881209, -0.07831693, -0.06005137, ...,  0.05956706,
           0.05636967,  0.05397416]]]], dtype=float32), array([[[[ 0.35793608,  0.38650516,  0.41237137, ..., -0.10680291,
          -0.1166895 , -0.10799987],
         [ 0.35609576,  0.3837929 ,  0.40842965, ..., -0.08566464,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b6c0b68bb70>, (<function concrete at 0x2b6b8be2ea60>, [[[[array([[[[-0.005786  , -0.00743728, -0.00926671, ..., -0.17115279,
          -0.16293609, -0.15400253],
         [-0.00800922, -0.00961725, -0.01136618, ..., -0.16520269,
          -0.15696831, -0.14790156],
         [-0.01008329, -0.01166868, -0.01334331, ..., -0.15968442,
          -0.15138228, -0.142034  ],
         ...,
         [-0.06362565, -0.06394443, -0.06396454, ..., -0.03132667,
          -0.02816841, -0.02478644],
         [-0.06390025, -0.06434818, -0.064535  , ..., -0.02800839,
          -0.02500737, -0.02171498],
         [-0.06384893, -0.0643828 , -0.06471166, ..., -0.02432125,
          -0.02132711, -0.01806376]]]], dtype=float32), array([[[[-0.14594233, -0.14064896, -0.13876148, ..., -0.2434047 ,
          -0.24247564, -0.24055022],
         [-0.1397813 , -0.13460295, -0.13289808, ..., -0.24953339,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b6c0bb4fae8>, (<function concrete at 0x2b6b8be2ea60>, [[[[array([[[[0.17958102, 0.18795435, 0.19459167, ..., 0.12312554,
          0.12321143, 0.12345281],
         [0.16232805, 0.17129454, 0.17907086, ..., 0.12468836,
          0.12491744, 0.1253173 ],
         [0.14800254, 0.15607296, 0.16346332, ..., 0.12442496,
          0.12497619, 0.1256926 ],
         ...,
         [0.05722329, 0.05684797, 0.05720201, ..., 0.07186034,
          0.07657785, 0.0814088 ],
         [0.05853456, 0.05764001, 0.05764504, ..., 0.06613801,
          0.07141038, 0.07621794],
         [0.06069008, 0.05907148, 0.05853426, ..., 0.05709269,
          0.06397428, 0.0704774 ]]]], dtype=float32), array([[[[ 0.12380835,  0.12425099,  0.12476463, ...,  0.09178791,
           0.10836449,  0.11357392],
         [ 0.1258421 ,  0.12646617,  0.1271792 , ...,  0.09750839,
           0.10850686,  0.10987775],
         [ 0
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b6c0b94b158>, (<function concrete at 0x2b6b8be2ea60>, [[[[array([[[[-0.09060941, -0.08932926, -0.08584978, ..., -0.1047212 ,
          -0.11458687, -0.12315819],
         [-0.09855691, -0.09467819, -0.09000697, ..., -0.09862527,
          -0.10969808, -0.1195669 ],
         [-0.10057402, -0.09611426, -0.09334864, ..., -0.09345   ,
          -0.10585761, -0.11650094],
         ...,
         [ 0.1289911 ,  0.11432716,  0.09979844, ..., -0.0529262 ,
          -0.05932943, -0.06883699],
         [ 0.13499288,  0.12318566,  0.10862297, ..., -0.05398335,
          -0.05897463, -0.06743694],
         [ 0.1359863 ,  0.12897603,  0.11683605, ..., -0.0554523 ,
          -0.0595466 , -0.06630849]]]], dtype=float32), array([[[[-0.12885407, -0.1274245 , -0.11513807, ...,  0.05339158,
           0.05602542,  0.05704688],
         [-0.12561455, -0.12339424, -0.11071727, ...,  0.05683855,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b6c0b612598>, (<function concrete at 0x2b6b8be2ea60>, [[[[array([[[[ 0.05935702,  0.05793982,  0.05406502, ...,  0.01741875,
           0.02588723,  0.02341923],
         [ 0.04926167,  0.05493282,  0.05709179, ...,  0.00624328,
           0.02423349,  0.02717775],
         [ 0.03043196,  0.04064171,  0.05011567, ..., -0.00907495,
           0.01770919,  0.02835579],
         ...,
         [ 0.13317525,  0.13416676,  0.13211893, ...,  0.00131179,
           0.00298007,  0.00166077],
         [ 0.12105947,  0.12196621,  0.12010194, ...,  0.00740238,
           0.00710422,  0.00391726],
         [ 0.11008371,  0.11038018,  0.10835616, ...,  0.0131258 ,
           0.01114021,  0.00664272]]]], dtype=float32), array([[[[ 0.01630281,  0.00875045,  0.00243411, ...,  0.06151169,
           0.05867829,  0.05611159],
         [ 0.02196417,  0.01419582,  0.00692341, ...,  0.06328081,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b6c0b651730>, (<function concrete at 0x2b6b8be2ea60>, [[[[array([[[[-0.156431  , -0.17180718, -0.18649589, ..., -0.22841585,
          -0.244897  , -0.23897883],
         [-0.16127814, -0.17668031, -0.19133303, ..., -0.23472589,
          -0.24739711, -0.25306895],
         [-0.16628195, -0.1815516 , -0.19606182, ..., -0.24053548,
          -0.24820687, -0.2689462 ],
         ...,
         [-0.19301844, -0.18853138, -0.18337454, ..., -0.14722727,
          -0.14956929, -0.1439214 ],
         [-0.1902495 , -0.18578956, -0.18055855, ..., -0.13920714,
          -0.14642157, -0.14282952],
         [-0.1876557 , -0.18326163, -0.17797253, ..., -0.1293448 ,
          -0.13992715, -0.14073746]]]], dtype=float32), array([[[[-0.32235846, -0.25357127, -0.11468072, ...,  0.20839766,
           0.17140824,  0.12561148],
         [-0.3432314 , -0.16131371, -0.01295952, ...,  0.20626205,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b6c0b902b70>, (<function concrete at 0x2b6b8be2ea60>, [[[[array([[[[-0.03056754, -0.03275187, -0.03428673, ..., -0.02142008,
          -0.0204697 , -0.01929393],
         [-0.03058084, -0.03286117, -0.03453403, ..., -0.01963508,
          -0.01866217, -0.01749854],
         [-0.03054848, -0.0329114 , -0.03470191, ..., -0.01789518,
          -0.01689151, -0.01573244],
         ...,
         [-0.06459425, -0.06129202, -0.06007646, ...,  0.00138572,
           0.00038565, -0.00133876],
         [-0.07423944, -0.07263605, -0.07095436, ..., -0.02145963,
          -0.02166437, -0.02188178],
         [ 0.        ,  0.        ,  0.        , ...,  0.        ,
           0.        ,  0.        ]]]], dtype=float32), array([[[[-0.01788322, -0.01623198, -0.01433915, ...,  0.        ,
           0.        ,  0.        ],
         [-0.01612872, -0.01454391, -0.01274532, ...,  0.        ,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b6c0b9ac598>, (<function concrete at 0x2b6b8be2ea60>, [[[[array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]]), array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]]), array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]])], [array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ...
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b6c0bc09378>, (<function concrete at 0x2b6b8be2ea60>, [[[[array([[[[-0.03160356, -0.01733894, -0.004734  , ..., -0.05436974,
          -0.05231908, -0.04809473],
         [-0.03438464, -0.02028029, -0.00724765, ..., -0.04842449,
          -0.04825738, -0.04581618],
         [-0.03549277, -0.02241605, -0.00946469, ..., -0.04138469,
          -0.04219725, -0.04206746],
         ...,
         [ 0.03432782,  0.03403798,  0.03275384, ..., -0.00776293,
          -0.00679897, -0.0051444 ],
         [ 0.02999747,  0.03016274,  0.02953249, ..., -0.00767659,
          -0.00756062, -0.00682593],
         [ 0.02454509,  0.02405743,  0.02317124, ..., -0.0080615 ,
          -0.00867773, -0.00870804]]]], dtype=float32), array([[[[-0.04268917, -0.03703265, -0.03167487, ..., -0.03116404,
          -0.02329743, -0.01627519],
         [-0.04130816, -0.03599804, -0.03077908, ..., -0.03142008,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b6c0bbf5048>, (<function concrete at 0x2b6b8be2ea60>, [[[[array([[[[-0.15752989, -0.16068242, -0.16311182, ..., -0.2434047 ,
          -0.24247564, -0.24055022],
         [-0.15313266, -0.15719315, -0.16056818, ..., -0.24953339,
          -0.24838625, -0.24574114],
         [-0.14792961, -0.15278065, -0.15700595, ..., -0.25542873,
          -0.25425974, -0.25113052],
         ...,
         [-0.11652103, -0.1205568 , -0.12402537, ..., -0.21560664,
          -0.21616536, -0.21570437],
         [-0.11819145, -0.12179592, -0.12481254, ..., -0.2141969 ,
          -0.21440034, -0.21318781],
         [-0.11990134, -0.12293588, -0.1253983 , ..., -0.21303436,
          -0.21261506, -0.21050711]]]], dtype=float32), array([[[[-0.23879959, -0.23852508, -0.24036804, ...,  0.10956795,
           0.10642271,  0.10264309],
         [-0.24276167, -0.24097066, -0.24154186, ...,  0.10192595,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b6c0b6ecc80>, (<function concrete at 0x2b6b8be2ea60>, [[[[array([[[[0.12413462, 0.11990102, 0.11383114, ..., 0.05339158,
          0.05602542, 0.05704688],
         [0.12274298, 0.11889074, 0.11322907, ..., 0.05683855,
          0.05848597, 0.05830446],
         [0.1214182 , 0.11749806, 0.11194748, ..., 0.06004746,
          0.06076254, 0.05952026],
         ...,
         [0.06451507, 0.06118069, 0.0583079 , ..., 0.07522827,
          0.06878252, 0.06099449],
         [0.06487711, 0.0611025 , 0.05775742, ..., 0.07561573,
          0.07460947, 0.0688035 ],
         [0.06383654, 0.05989832, 0.0566719 , ..., 0.07066231,
          0.07241981, 0.07200576]]]], dtype=float32), array([[[[0.05557374, 0.05130705, 0.04580517, ..., 0.        ,
          0.        , 0.        ],
         [0.05555202, 0.05054621, 0.04516842, ..., 0.        ,
          0.        , 0.        ],
         [0.05586899, 0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.170:47284 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.170:47264 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.170:47054 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.170:47148 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.170:47020 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.170:47192 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.170:47146 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.170:47056 remote=tcp://172.30.100.1:40264>
distributed.worker - INFO - Timed out when connecting to scheduler
distributed.worker - INFO - Stopping worker at tcp://172.30.6.170:41914
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.170:39171'
distributed.dask_worker - INFO - End worker
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-3, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-28, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-15, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-2, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-22, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-18, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-10, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-1, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-6, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-26, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-21, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-17, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-25, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-9, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-5, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-13, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-14, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-27, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-20, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-16, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-24, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-4, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-8, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-12, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-19, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-7, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-11, started daemon)>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
