/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:46012'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:42889'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:44524'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:45085'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:39473'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:46436'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:44089'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:38289'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:35134'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:38885'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:45067'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:35893'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:40318'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:39961'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:32845'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:36946'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:38342'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:36075'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:43794'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:41680'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:43664'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:34113'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:34108'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:39600'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:35496'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:43544'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:45159'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.214:36684'
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:44674
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:45876
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:44926
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:44674
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:37406
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:45876
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:39491
distributed.worker - INFO -              nanny at:         172.30.8.214:36946
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:44926
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:37406
distributed.worker - INFO -              nanny at:         172.30.8.214:43794
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:37811
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:43700
distributed.worker - INFO -              bokeh at:         172.30.8.214:40026
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:39491
distributed.worker - INFO -              nanny at:         172.30.8.214:46012
distributed.worker - INFO -              nanny at:         172.30.8.214:42889
distributed.worker - INFO -              bokeh at:         172.30.8.214:40429
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:37811
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:43700
distributed.worker - INFO -              bokeh at:         172.30.8.214:37842
distributed.worker - INFO -              nanny at:         172.30.8.214:38885
distributed.worker - INFO -              bokeh at:         172.30.8.214:41235
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:         172.30.8.214:44089
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO -              nanny at:         172.30.8.214:38289
distributed.worker - INFO -              bokeh at:         172.30.8.214:40971
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -              bokeh at:         172.30.8.214:41395
distributed.worker - INFO -              bokeh at:         172.30.8.214:42543
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-ygi228nl
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-6zws3_hq
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-hw4fpfrk
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-t3egetby
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-c_nidjs2
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-k96943f0
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-lepe38r7
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:32801
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:32801
distributed.worker - INFO -              nanny at:         172.30.8.214:35134
distributed.worker - INFO -              bokeh at:         172.30.8.214:43996
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-zcdos7u_
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:37671
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:37671
distributed.worker - INFO -              nanny at:         172.30.8.214:35496
distributed.worker - INFO -              bokeh at:         172.30.8.214:43171
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-_kapgrjt
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:36002
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:36002
distributed.worker - INFO -              nanny at:         172.30.8.214:39600
distributed.worker - INFO -              bokeh at:         172.30.8.214:37962
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-xtja3wca
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:43851
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:43851
distributed.worker - INFO -              nanny at:         172.30.8.214:39473
distributed.worker - INFO -              bokeh at:         172.30.8.214:35512
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-3osbn3hx
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:40242
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:41681
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:40242
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:41681
distributed.worker - INFO -              nanny at:         172.30.8.214:44524
distributed.worker - INFO -              nanny at:         172.30.8.214:40318
distributed.worker - INFO -              bokeh at:         172.30.8.214:32886
distributed.worker - INFO -              bokeh at:         172.30.8.214:39388
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-4gw5hoox
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-6pa9t4x6
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:37740
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:37740
distributed.worker - INFO -              nanny at:         172.30.8.214:38342
distributed.worker - INFO -              bokeh at:         172.30.8.214:32952
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-vm39uick
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:35086
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:35086
distributed.worker - INFO -              nanny at:         172.30.8.214:43664
distributed.worker - INFO -              bokeh at:         172.30.8.214:41551
distributed.core - INFO - Starting established connection
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:34267
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:34267
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-p_4j_myx
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:         172.30.8.214:34113
distributed.worker - INFO -              bokeh at:         172.30.8.214:43309
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-e8f2k0qp
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:38035
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:38035
distributed.worker - INFO -              nanny at:         172.30.8.214:45159
distributed.worker - INFO -              bokeh at:         172.30.8.214:42383
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-i03tekh9
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:46435
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:46435
distributed.worker - INFO -              nanny at:         172.30.8.214:41680
distributed.worker - INFO -              bokeh at:         172.30.8.214:36618
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-gdd7tg4d
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:36729
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:36729
distributed.worker - INFO -              nanny at:         172.30.8.214:43544
distributed.worker - INFO -              bokeh at:         172.30.8.214:39745
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-ujel0m3n
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:40513
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:40513
distributed.worker - INFO -              nanny at:         172.30.8.214:36075
distributed.worker - INFO -              bokeh at:         172.30.8.214:44164
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-amuecfo9
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:38594
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:38594
distributed.worker - INFO -              nanny at:         172.30.8.214:45085
distributed.worker - INFO -              bokeh at:         172.30.8.214:44124
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-3x6ew67t
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:44720
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:44720
distributed.worker - INFO -              nanny at:         172.30.8.214:32845
distributed.worker - INFO -              bokeh at:         172.30.8.214:33952
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-1uqsh20o
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:35869
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:35869
distributed.worker - INFO -              nanny at:         172.30.8.214:35893
distributed.worker - INFO -              bokeh at:         172.30.8.214:37917
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-19vbcxlg
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:36523
distributed.core - INFO - Starting established connection
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:36523
distributed.worker - INFO -              nanny at:         172.30.8.214:34108
distributed.worker - INFO -              bokeh at:         172.30.8.214:38716
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-kq4wm_50
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:35666
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:35666
distributed.worker - INFO -              nanny at:         172.30.8.214:46436
distributed.worker - INFO -              bokeh at:         172.30.8.214:37142
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-cmlb60uh
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:41963
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:41963
distributed.worker - INFO -              nanny at:         172.30.8.214:39961
distributed.worker - INFO -              bokeh at:         172.30.8.214:42861
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-3dm7f41h
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:33761
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:33761
distributed.worker - INFO -              nanny at:         172.30.8.214:45067
distributed.worker - INFO -              bokeh at:         172.30.8.214:34676
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-vxq5ckd6
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.214:32822
distributed.worker - INFO -          Listening to:   tcp://172.30.8.214:32822
distributed.worker - INFO -              nanny at:         172.30.8.214:36684
distributed.worker - INFO -              bokeh at:         172.30.8.214:40989
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-gegy7lj0
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b9f19bd5208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b9f19bd5208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b9f19bd5208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53226 remote=tcp://172.30.100.2:37747>
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b9f19bd5208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b9f19bd5208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53280 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53406 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53404 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b9f19bd5208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b9f19bd5208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b9f19bd5208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b9f19bd5208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53588 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53592 remote=tcp://172.30.100.2:37747>
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b9f19bd5208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b9f19bd5208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b9f19bd5208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b9f19bd5208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53590 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53650 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53766 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53806 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53614 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53276 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53628 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53314 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53688 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53710 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53442 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53494 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53528 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53278 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53654 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53690 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53340 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53728 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53382 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53532 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53596 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53268 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53656 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53342 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53716 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53730 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53380 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53452 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53572 remote=tcp://172.30.100.2:37747>
distributed.utils_perf - INFO - full garbage collection released 56.76 MB from 1564 reference cycles (threshold: 10.00 MB)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:52878 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53600 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53274 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53302 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53668 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53740 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53514 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53540 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53554 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:54020 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53680 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53714 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53432 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53492 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53570 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53696 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53754 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:54032 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53216 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53476 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53092 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53648 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53184 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53808 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53330 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53722 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53372 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53444 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53502 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53530 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53224 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53146 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53698 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53366 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53756 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53244 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53312 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53816 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53290 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53644 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53674 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53752 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53800 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53490 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53546 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53606 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53138 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53284 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53636 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53664 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53692 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53738 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53584 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:54018 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53474 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53090 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53651 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53538 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53188 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53332 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53720 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53370 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53446 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53500 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53602 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53286 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53638 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53300 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53666 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53742 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53460 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53542 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:54022 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53594 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53098 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53574 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53266 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53506 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53412 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53248 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53178 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53684 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53704 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53436 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53802 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53468 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53496 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53522 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53762 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:54036 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53210 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53416 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53536 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53294 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53706 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53438 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53180 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53626 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53686 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53326 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53708 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53440 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53526 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53578 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53764 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:54038 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53678 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53750 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53798 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53486 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53586 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53612 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:54030 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53144 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53700 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53368 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53758 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53308 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53810 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53814 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53292 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53642 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53672 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53746 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53398 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53534 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53544 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53608 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53782 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53598 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53270 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53658 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53344 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53712 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53736 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53386 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53458 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53568 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:54016 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53310 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53818 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53646 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53676 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53748 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53784 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53462 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53488 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53548 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53610 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53150 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53682 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53702 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53434 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53803 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53470 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53524 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53760 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:54034 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53096 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53718 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53726 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53450 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53282 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53778 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53660 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53346 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53734 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53384 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53796 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53454 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53512 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53580 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:54012 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53780 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53272 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53662 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53348 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53732 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53388 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53456 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53582 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:54014 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53240 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53304 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53288 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53640 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53670 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53744 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53396 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53694 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53478 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53094 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53186 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53334 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53724 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53374 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53448 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:53504 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.214:54040 remote=tcp://172.30.100.2:37747>
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - INFO - -------------------------------------------------
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.utils_perf - INFO - full garbage collection released 47.29 MB from 5884 reference cycles (threshold: 10.00 MB)
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.utils_perf - INFO - full garbage collection released 44.25 MB from 6580 reference cycles (threshold: 10.00 MB)
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:45876
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:32801
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:44720
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:44926
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:43794'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:41681
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:35134'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:37811
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:32845'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:40242
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:46012'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:35086
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:37740
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:40318'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:43700
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:34267
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:39491
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:44674
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:44089'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:44524'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:37671
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:38035
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:36729
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:43664'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:46435
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:38342'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:36523
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:38289'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:43851
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:34113'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:38594
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:32822
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:33761
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:40513
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:36946'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:35666
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:41963
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:41680'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:43544'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:34108'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:39473'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:36684'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:45067'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:36075'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:46436'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:39961'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:35496'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:45159'
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:35869
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:35893'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:45085'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:38885'
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:36002
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:39600'
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Stopping worker at tcp://172.30.8.214:37406
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.214:42889'
distributed.dask_worker - INFO - End worker
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
