/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:36194'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:37296'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:34011'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:42266'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:42550'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:37636'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:40749'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:42792'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:34491'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:39533'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:46686'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:33266'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:35516'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:44988'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:38429'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:37809'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:39702'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:38006'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:35183'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:40652'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:35296'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:39626'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:43864'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:38472'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:36520'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:40211'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:38597'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.211:32935'
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:36008
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:36008
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:34323
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:39781
distributed.worker - INFO -              nanny at:         172.30.8.211:37809
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:34323
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:39781
distributed.worker - INFO -              bokeh at:         172.30.8.211:41985
distributed.worker - INFO -              nanny at:         172.30.8.211:46686
distributed.worker - INFO -              nanny at:         172.30.8.211:36194
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO -              bokeh at:         172.30.8.211:44778
distributed.worker - INFO -              bokeh at:         172.30.8.211:38298
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-dy0r0gp7
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-__csz0gl
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-m0gwzs2_
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:43457
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:43457
distributed.worker - INFO -              nanny at:         172.30.8.211:36520
distributed.worker - INFO -              bokeh at:         172.30.8.211:34448
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-zmqvmrm6
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:34889
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:34889
distributed.worker - INFO -              nanny at:         172.30.8.211:34011
distributed.worker - INFO -              bokeh at:         172.30.8.211:42951
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-q1ygm3_8
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:39538
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:39538
distributed.worker - INFO -              nanny at:         172.30.8.211:39626
distributed.worker - INFO -              bokeh at:         172.30.8.211:45621
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-n6e8_lsx
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:38715
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:38715
distributed.worker - INFO -              nanny at:         172.30.8.211:34491
distributed.worker - INFO -              bokeh at:         172.30.8.211:35046
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-aq3njohl
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:40986
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:40986
distributed.worker - INFO -              nanny at:         172.30.8.211:35296
distributed.worker - INFO -              bokeh at:         172.30.8.211:42904
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-xy3vin4l
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:37803
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:37803
distributed.worker - INFO -              nanny at:         172.30.8.211:38597
distributed.worker - INFO -              bokeh at:         172.30.8.211:44910
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:46573
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-54g5w8_h
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:46573
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:         172.30.8.211:42550
distributed.worker - INFO -              bokeh at:         172.30.8.211:38871
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-302n8o5m
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:42197
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:42197
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:         172.30.8.211:39702
distributed.worker - INFO -              bokeh at:         172.30.8.211:33833
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-umf1pv1o
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:37139
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:37139
distributed.worker - INFO -              nanny at:         172.30.8.211:38472
distributed.worker - INFO -              bokeh at:         172.30.8.211:36816
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-c3h5myzn
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:37852
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:37852
distributed.worker - INFO -              nanny at:         172.30.8.211:37636
distributed.worker - INFO -              bokeh at:         172.30.8.211:34472
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-ljijnbk6
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:37957
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:37957
distributed.worker - INFO -              nanny at:         172.30.8.211:37296
distributed.worker - INFO -              bokeh at:         172.30.8.211:43285
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-7soopbww
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:43889
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:43889
distributed.worker - INFO -              nanny at:         172.30.8.211:39533
distributed.worker - INFO -              bokeh at:         172.30.8.211:36696
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-95rgz75a
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:41912
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:41912
distributed.worker - INFO -              nanny at:         172.30.8.211:43864
distributed.worker - INFO -              bokeh at:         172.30.8.211:44744
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-hn8c425d
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:42714
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:42714
distributed.worker - INFO -              nanny at:         172.30.8.211:42792
distributed.worker - INFO -              bokeh at:         172.30.8.211:40000
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-v9hptoko
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:35975
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:35975
distributed.worker - INFO -              nanny at:         172.30.8.211:40652
distributed.worker - INFO -              bokeh at:         172.30.8.211:41700
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-_7h3x3vw
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:42444
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:42444
distributed.worker - INFO -              nanny at:         172.30.8.211:44988
distributed.worker - INFO -              bokeh at:         172.30.8.211:43772
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:44221
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-obghs1ki
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:44221
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:         172.30.8.211:35183
distributed.worker - INFO -              bokeh at:         172.30.8.211:38781
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-5ndzxrsf
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:36983
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:36983
distributed.worker - INFO -              nanny at:         172.30.8.211:35516
distributed.worker - INFO -              bokeh at:         172.30.8.211:39465
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-depdsj5b
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:40775
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:40775
distributed.worker - INFO -              nanny at:         172.30.8.211:38429
distributed.worker - INFO -              bokeh at:         172.30.8.211:39621
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-iyfsay0i
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:40498
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:40498
distributed.worker - INFO -              nanny at:         172.30.8.211:38006
distributed.worker - INFO -              bokeh at:         172.30.8.211:36774
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-ku_uqfmt
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:40680
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:40680
distributed.worker - INFO -              nanny at:         172.30.8.211:33266
distributed.worker - INFO -              bokeh at:         172.30.8.211:37353
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-pq7d1h63
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:37291
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:37291
distributed.worker - INFO -              nanny at:         172.30.8.211:32935
distributed.worker - INFO -              bokeh at:         172.30.8.211:40984
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-thtc0g4r
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:42926
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:42926
distributed.worker - INFO -              nanny at:         172.30.8.211:40749
distributed.worker - INFO -              bokeh at:         172.30.8.211:36647
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-9c8e_4g1
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:35877
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:35877
distributed.worker - INFO -              nanny at:         172.30.8.211:40211
distributed.worker - INFO -              bokeh at:         172.30.8.211:40176
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-0a9sok5i
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.211:36376
distributed.worker - INFO -          Listening to:   tcp://172.30.8.211:36376
distributed.worker - INFO -              nanny at:         172.30.8.211:42266
distributed.worker - INFO -              bokeh at:         172.30.8.211:39335
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-v4cedgxd
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.utils_perf - INFO - full garbage collection released 15.46 MB from 342 reference cycles (threshold: 10.00 MB)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.utils_perf - INFO - full garbage collection released 15.45 MB from 271 reference cycles (threshold: 10.00 MB)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b96a0623208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48498 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48496 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48482 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48494 remote=tcp://172.30.100.2:37747>
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b96a0623208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48662 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48668 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48664 remote=tcp://172.30.100.2:37747>
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b96a0623208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b96a0623208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b96a0623208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b96a0623208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b96a0623208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b96a0623208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49026 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49028 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49032 remote=tcp://172.30.100.2:37747>
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b96a0623208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b96a0623208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b96a0623208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b96a0623208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49036 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49038 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49070 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49072 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48722 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48860 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48760 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48298 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48980 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48666 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48724 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48754 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49094 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49174 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48854 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48880 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49114 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49192 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49236 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48758 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49106 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49132 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48900 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48950 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49464 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49096 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49176 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48882 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49116 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48538 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49078 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49200 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48744 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49064 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48792 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49152 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48832 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48914 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48958 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49452 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48534 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49074 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49140 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49150 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48828 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48906 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49008 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49238 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49110 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48786 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49138 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48826 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48952 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48978 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49470 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48730 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48770 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49178 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49216 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48884 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49024 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49118 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49196 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48784 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49136 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48824 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48904 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48976 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49468 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48728 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48804 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49018 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49164 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48590 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49244 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49068 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49066 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48892 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48934 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49124 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49184 remote=tcp://172.30.100.2:37747>
distributed.utils_perf - INFO - full garbage collection released 21.50 MB from 1757 reference cycles (threshold: 10.00 MB)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48674 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48648 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49102 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49126 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48894 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49186 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49218 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48888 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48932 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49006 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49020 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49214 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49090 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49170 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48926 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48544 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49084 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48800 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49146 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49162 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48920 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49034 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48548 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48778 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48802 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49158 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48918 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48986 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49458 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49194 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49042 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49050 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48738 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48756 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49108 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48782 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49134 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48902 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48974 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49466 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48536 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49198 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49044 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48740 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49142 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49148 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48830 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48908 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49010 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49016 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49450 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48752 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48732 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49060 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49092 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49172 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48852 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48928 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48858 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48688 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49242 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49062 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49098 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48772 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48886 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48964 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48988 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49120 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49180 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49030 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48546 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49144 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49160 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48916 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49012 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48502 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48946 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49088 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48766 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48808 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48848 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48924 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49166 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48540 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49080 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48984 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49202 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48742 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48794 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49154 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48836 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48912 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48954 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49456 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48736 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48982 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48628 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49130 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48898 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48970 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49190 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48500 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48944 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49086 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48764 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48806 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48846 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48922 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48962 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49168 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49076 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49204 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48746 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48796 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49156 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48834 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48910 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48956 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49454 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49104 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49128 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48896 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49022 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49188 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49462 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48734 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49100 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:48890 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49122 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.211:49182 remote=tcp://172.30.100.2:37747>
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - INFO - -------------------------------------------------
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.utils_perf - INFO - full garbage collection released 24.04 MB from 7215 reference cycles (threshold: 10.00 MB)
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.utils_perf - INFO - full garbage collection released 47.28 MB from 7555 reference cycles (threshold: 10.00 MB)
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.utils_perf - INFO - full garbage collection released 96.12 MB from 8245 reference cycles (threshold: 10.00 MB)
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:40986
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:36983
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:44221
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:40775
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:35296'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:40498
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:36008
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:39781
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:35516'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:35183'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:38429'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:38006'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:37809'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:42714
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:34323
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:36194'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:46573
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:40680
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:37852
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:43457
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:36376
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:42926
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:37803
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:38715
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:43889
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:34889
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:39538
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:42550'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:33266'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:36520'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:37636'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:46686'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:42266'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:34011'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:40749'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:34491'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:42792'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:38597'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:39533'
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:41912
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:43864'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:42197
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:39702'
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:37957
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:37296'
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:37291
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:32935'
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:39626'
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:35877
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:40211'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:35975
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:40652'
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:42444
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:44988'
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Stopping worker at tcp://172.30.8.211:37139
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.211:38472'
distributed.dask_worker - INFO - End worker
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
