/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:46083'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:41221'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:37762'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:40593'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:44550'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:45392'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:43151'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:37909'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:39300'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:38483'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:45822'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:46158'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:37194'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:32804'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:35106'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:37301'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:43481'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:37919'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:45288'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:44283'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:36712'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:46087'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:46779'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:44604'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:37393'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:34548'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:38051'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.169:41837'
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:44246
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:44246
distributed.worker - INFO -              nanny at:         172.30.6.169:44550
distributed.worker - INFO -              bokeh at:         172.30.6.169:38059
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-9fbg21bq
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:41186
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:41186
distributed.worker - INFO -              nanny at:         172.30.6.169:44604
distributed.worker - INFO -              bokeh at:         172.30.6.169:40933
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-h0_w94od
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:35362
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:35362
distributed.worker - INFO -              nanny at:         172.30.6.169:37301
distributed.worker - INFO -              bokeh at:         172.30.6.169:43168
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-wgrvuzfe
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:43620
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:43620
distributed.worker - INFO -              nanny at:         172.30.6.169:37909
distributed.worker - INFO -              bokeh at:         172.30.6.169:39608
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-d6tzu2mz
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:45464
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:45464
distributed.worker - INFO -              nanny at:         172.30.6.169:46087
distributed.worker - INFO -              bokeh at:         172.30.6.169:45656
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-3scd2rmk
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:32881
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:32881
distributed.worker - INFO -              nanny at:         172.30.6.169:37393
distributed.worker - INFO -              bokeh at:         172.30.6.169:34923
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-ewr6wl35
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:45050
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:45050
distributed.worker - INFO -              nanny at:         172.30.6.169:38483
distributed.worker - INFO -              bokeh at:         172.30.6.169:40653
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-xugv07l7
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:33255
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:33255
distributed.worker - INFO -              nanny at:         172.30.6.169:35106
distributed.worker - INFO -              bokeh at:         172.30.6.169:41736
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-jw1oiwww
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:33384
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:33384
distributed.worker - INFO -              nanny at:         172.30.6.169:43481
distributed.worker - INFO -              bokeh at:         172.30.6.169:40723
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-zochaxm3
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:42915
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:42915
distributed.worker - INFO -              nanny at:         172.30.6.169:46779
distributed.worker - INFO -              bokeh at:         172.30.6.169:40886
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-2bhylwhm
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:33378
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:33378
distributed.worker - INFO -              nanny at:         172.30.6.169:40593
distributed.worker - INFO -              bokeh at:         172.30.6.169:44976
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-il6gu480
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:46532
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:46532
distributed.worker - INFO -              nanny at:         172.30.6.169:43151
distributed.worker - INFO -              bokeh at:         172.30.6.169:37690
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-e9h333ik
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:33575
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:33575
distributed.worker - INFO -              nanny at:         172.30.6.169:46158
distributed.worker - INFO -              bokeh at:         172.30.6.169:45293
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-uox0895s
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:34534
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:34534
distributed.worker - INFO -              nanny at:         172.30.6.169:36712
distributed.worker - INFO -              bokeh at:         172.30.6.169:39732
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-dqsug0zg
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:39723
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:39723
distributed.worker - INFO -              nanny at:         172.30.6.169:37762
distributed.worker - INFO -              bokeh at:         172.30.6.169:46479
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-h7fztopy
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:46342
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:46342
distributed.worker - INFO -              nanny at:         172.30.6.169:39300
distributed.worker - INFO -              bokeh at:         172.30.6.169:43807
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-wjep5msl
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:40173
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:40173
distributed.worker - INFO -              nanny at:         172.30.6.169:44283
distributed.worker - INFO -              bokeh at:         172.30.6.169:40093
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-5o_bsstk
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:38453
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:38453
distributed.worker - INFO -              nanny at:         172.30.6.169:38051
distributed.worker - INFO -              bokeh at:         172.30.6.169:41994
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-sylk49x7
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:38484
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:38484
distributed.worker - INFO -              nanny at:         172.30.6.169:41221
distributed.worker - INFO -              bokeh at:         172.30.6.169:39079
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-g9agy7sq
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:32903
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:32903
distributed.worker - INFO -              nanny at:         172.30.6.169:46083
distributed.worker - INFO -              bokeh at:         172.30.6.169:43388
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-gcjy20yu
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:43374
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:43374
distributed.worker - INFO -              nanny at:         172.30.6.169:37194
distributed.worker - INFO -              bokeh at:         172.30.6.169:40534
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-s33ukkfx
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:41850
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:41850
distributed.worker - INFO -              nanny at:         172.30.6.169:45822
distributed.worker - INFO -              bokeh at:         172.30.6.169:42286
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-47kjwxoq
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:37186
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:37186
distributed.worker - INFO -              nanny at:         172.30.6.169:32804
distributed.worker - INFO -              bokeh at:         172.30.6.169:46218
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:42996
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:42996
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-kxdqiz7p
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:         172.30.6.169:37919
distributed.worker - INFO -              bokeh at:         172.30.6.169:40567
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:42973
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:42973
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:         172.30.6.169:45392
distributed.worker - INFO -              bokeh at:         172.30.6.169:45881
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-t7qoxeez
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-yr75j47r
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:46012
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:46012
distributed.worker - INFO -              nanny at:         172.30.6.169:34548
distributed.worker - INFO -              bokeh at:         172.30.6.169:41693
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-_jfgbm4g
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:38058
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:38058
distributed.worker - INFO -              nanny at:         172.30.6.169:45288
distributed.worker - INFO -              bokeh at:         172.30.6.169:42528
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-8ga8zd0r
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.169:35156
distributed.worker - INFO -          Listening to:   tcp://172.30.6.169:35156
distributed.worker - INFO -              nanny at:         172.30.6.169:41837
distributed.worker - INFO -              bokeh at:         172.30.6.169:38221
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-jpvavyj6
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Event loop was unresponsive in Worker for 163.16s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 163.16s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 163.16s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 163.22s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1c1a8b8c8>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[-0.02988647, -0.02972769, -0.02970022, ..., -0.11656286,
          -0.11519766, -0.11407372],
         [-0.0304336 , -0.03073474, -0.03120377, ..., -0.10958282,
          -0.10769745, -0.10620414],
         [-0.03103939, -0.03175168, -0.03262413, ..., -0.10195766,
          -0.09966522, -0.097914  ],
         ...,
         [-0.02391969, -0.02376259, -0.02369645, ...,  0.00666082,
           0.01617711,  0.02599256],
         [-0.02282198, -0.02259093, -0.02244636, ...,  0.0077598 ,
           0.01707067,  0.02654881],
         [-0.02170756, -0.02141642, -0.02122122, ...,  0.00879807,
           0.0178611 ,  0.02688195]]]], dtype=float32), array([[[[-0.11338217, -0.11313285, -0.11312611, ..., -0.19068989,
          -0.19634897, -0.20067056],
         [-0.10526691, -0.10488913, -0.10489176, ..., -0.1918561 ,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1c1ce8598>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[-0.05440765, -0.0464126 , -0.03799837, ...,  0.30959895,
           0.30379927,  0.29966402],
         [-0.05849355, -0.05032436, -0.0417146 , ...,  0.31390163,
           0.30847985,  0.30445272],
         [-0.06277941, -0.05432851, -0.04545777, ...,  0.31808108,
           0.31299195,  0.30917454],
         ...,
         [ 0.03021561,  0.05606255,  0.08439384, ...,  0.50577736,
           0.5122796 ,  0.51814026],
         [ 0.03530153,  0.06375572,  0.09446371, ...,  0.50915384,
           0.5150676 ,  0.5196633 ],
         [ 0.04235127,  0.07314476,  0.1059152 , ...,  0.51188236,
           0.5169848 ,  0.5199552 ]]]], dtype=float32), array([[[[0.29669848, 0.29534987, 0.29588035, ..., 0.07386237,
          0.09079354, 0.12237515],
         [0.3017961 , 0.30106834, 0.3023275 , ..., 0.08051246,
          0.11750919, 0
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1c1112f28>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[ 0.00971529,  0.00999534,  0.01058974, ..., -0.01362631,
          -0.01979844, -0.02585551],
         [ 0.00956856,  0.00971352,  0.01057198, ..., -0.01874528,
          -0.02433484, -0.0295949 ],
         [ 0.00989279,  0.01022804,  0.0116372 , ..., -0.02328116,
          -0.028238  , -0.03264428],
         ...,
         [ 0.0301659 ,  0.02635315,  0.02294957, ..., -0.05274932,
          -0.05106684, -0.04942601],
         [ 0.03239813,  0.02838026,  0.02462579, ..., -0.05479444,
          -0.05310866, -0.05148853],
         [ 0.03418429,  0.03028969,  0.02639506, ..., -0.05703915,
          -0.05534112, -0.0537237 ]]]], dtype=float32), array([[[[-0.03090543, -0.03416179, -0.03549201, ...,  0.03699397,
           0.03703456,  0.03673899],
         [-0.03369806, -0.0360411 , -0.03674183, ...,  0.04440076,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1c1147840>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[ 0.01144057,  0.01233197,  0.01307562, ..., -0.03121233,
          -0.03554357, -0.0385281 ],
         [ 0.01409009,  0.01506437,  0.0161654 , ..., -0.03319689,
          -0.03686572, -0.03915603],
         [ 0.0183977 ,  0.01957823,  0.02111368, ..., -0.03432286,
          -0.03739528, -0.03913449],
         ...,
         [ 0.0412666 ,  0.03827478,  0.03482997, ..., -0.04634068,
          -0.04438925, -0.04297266],
         [ 0.04110472,  0.03886684,  0.03588013, ..., -0.04769113,
          -0.04589483, -0.0446481 ],
         [ 0.0396668 ,  0.03839241,  0.03615695, ..., -0.04932486,
          -0.04766405, -0.04653731]]]], dtype=float32), array([[[[-0.03958966, -0.03889134, -0.03744994, ...,  0.04823182,
           0.0496145 ,  0.05037468],
         [-0.03976211, -0.03899157, -0.03775776, ...,  0.0555357 ,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1c143b7b8>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[ 0.0289439 ,  0.03591153,  0.04330626, ...,  0.24628048,
           0.23891474,  0.23095214],
         [ 0.03031733,  0.0374834 ,  0.04511287, ...,  0.23397131,
           0.22616492,  0.21789815],
         [ 0.0317631 ,  0.03905563,  0.04684473, ...,  0.22192758,
           0.21380362,  0.20528837],
         ...,
         [-0.05683994, -0.05703032, -0.05721187, ...,  0.16442072,
           0.16686861,  0.16729406],
         [-0.05514064, -0.05542935, -0.05567014, ...,  0.16171704,
           0.16290419,  0.16328621],
         [-0.05210831, -0.05247487, -0.05272629, ...,  0.15694974,
           0.15837435,  0.15952113]]]], dtype=float32), array([[[[ 0.22249158,  0.21360517,  0.20432077, ..., -0.06860411,
          -0.0568827 , -0.04360769],
         [ 0.20922202,  0.2001587 ,  0.19073506, ..., -0.07926279,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1c13841e0>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[ 0.12813807,  0.13889189,  0.14856316, ...,  0.26189512,
           0.2597621 ,  0.25726762],
         [ 0.10732676,  0.11857896,  0.1292947 , ...,  0.25173658,
           0.24873893,  0.2454126 ],
         [ 0.08618977,  0.09615824,  0.10627327, ...,  0.23240595,
           0.22926384,  0.22580265],
         ...,
         [-0.1136953 , -0.11579264, -0.11758444, ..., -0.10452072,
          -0.10063533, -0.09641682],
         [-0.10565686, -0.10805832, -0.11000983, ..., -0.0863962 ,
          -0.0832771 , -0.08028874],
         [-0.09778681, -0.10064872, -0.10296429, ..., -0.06964206,
          -0.06520855, -0.06122781]]]], dtype=float32), array([[[[ 0.25442126,  0.25122148,  0.24766769, ..., -0.1021518 ,
          -0.10340808, -0.09756544],
         [ 0.24177335,  0.23783176,  0.23360218, ..., -0.10230274,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1c10e89d8>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[-3.8168244e-02, -3.7114657e-02, -3.5565428e-02, ...,
          -3.1729888e-02, -3.3349063e-02, -3.4935262e-02],
         [-3.8575757e-02, -3.8109448e-02, -3.7254184e-02, ...,
          -3.2175176e-02, -3.3784922e-02, -3.5391897e-02],
         [-3.8546547e-02, -3.8461570e-02, -3.8120277e-02, ...,
          -3.2768227e-02, -3.4408893e-02, -3.6107160e-02],
         ...,
         [-8.1939436e-02, -7.2901092e-02, -6.8767227e-02, ...,
           1.4040503e-02,  1.4439048e-02,  1.6848348e-02],
         [-7.0398963e-25,  7.9516572e-24,  5.6979423e-24, ...,
          -8.6457901e-24,  5.8673932e-24, -9.3711419e-23],
         [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
           0.0000000e+00,  0.0000000e+00,  0.0000000e+00]]]],
      dtype=float32), array([[[[-3.6520872e-02, -3.8169127e-02, -3.9918110e-02, ...,
       
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1c13ca510>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[-0.03203143, -0.0465414 , -0.06096122, ...,  0.2686129 ,
           0.27537292,  0.2760125 ],
         [-0.03271483, -0.0478113 , -0.06272963, ...,  0.2804457 ,
           0.2772135 ,  0.28088483],
         [-0.03306467, -0.04871966, -0.06418969, ...,  0.29710385,
           0.30942756,  0.32470042],
         ...,
         [ 0.06580997,  0.0693937 ,  0.07250738, ...,  0.19777045,
           0.15825541,  0.1297332 ],
         [ 0.06780788,  0.07197928,  0.0761257 , ...,  0.19188243,
           0.16571312,  0.13855554],
         [ 0.06998307,  0.07495708,  0.08048376, ...,  0.18056418,
           0.16388722,  0.14157954]]]], dtype=float32), array([[[[0.27646095, 0.28220692, 0.29276246, ..., 0.5506925 ,
          0.5243071 , 0.4902761 ],
         [0.287686  , 0.2691143 , 0.27313593, ..., 0.5553188 ,
          0.5288118 , 0
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1c1468268>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[-0.04048571, -0.0427159 , -0.04528116, ..., -0.04321569,
          -0.04342754, -0.0435672 ],
         [-0.04029002, -0.042506  , -0.04508326, ..., -0.04187034,
          -0.04197979, -0.04204057],
         [-0.04012069, -0.04231274, -0.04490074, ..., -0.04057208,
          -0.0405274 , -0.04047679],
         ...,
         [-0.06083077, -0.0590361 , -0.05923458, ..., -0.01977971,
          -0.01836348, -0.0169282 ],
         [-0.06628541, -0.06496028, -0.06357996, ..., -0.03132316,
          -0.03168845, -0.03205306],
         [ 0.        ,  0.        ,  0.        , ...,  0.        ,
           0.        ,  0.        ]]]], dtype=float32), array([[[[-0.04360402, -0.04351949, -0.04329123, ...,  0.        ,
           0.        ,  0.        ],
         [-0.04200432, -0.04184289, -0.04153923, ...,  0.        ,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1c103d950>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[ 0.08908157,  0.09451196,  0.10020561, ...,  0.18649861,
           0.20822583,  0.22878334],
         [ 0.09720407,  0.10302529,  0.10892379, ...,  0.1699074 ,
           0.18261765,  0.19450475],
         [ 0.10550386,  0.11162842,  0.11768609, ...,  0.15237935,
           0.15096226,  0.1552966 ],
         ...,
         [ 0.13927756,  0.13790067,  0.13621072, ...,  0.00170745,
          -0.00712974, -0.02438912],
         [ 0.1371692 ,  0.13571621,  0.13375159, ...,  0.0153619 ,
           0.00789155, -0.00488616],
         [ 0.1346883 ,  0.13324909,  0.13095793, ...,  0.02453377,
           0.01835035,  0.01356718]]]], dtype=float32), array([[[[ 0.26556292,  0.1937958 ,  0.07397214, ...,  0.10841642,
           0.1377956 ,  0.18048868],
         [ 0.21233772,  0.10044412,  0.01245668, ...,  0.09945572,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1c11e5400>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[-0.04327581, -0.05559144, -0.06880129, ..., -0.06860411,
          -0.0568827 , -0.04360769],
         [-0.0460503 , -0.05895643, -0.07279846, ..., -0.07926279,
          -0.06311836, -0.03575028],
         [-0.04912186, -0.06254111, -0.07692084, ..., -0.09778697,
          -0.08786769, -0.04546075],
         ...,
         [-0.07835294, -0.07455946, -0.07214209, ..., -0.06471707,
          -0.08451819, -0.04864547],
         [-0.0743232 , -0.07105795, -0.0691404 , ..., -0.05458884,
          -0.06997124, -0.03638053],
         [-0.07051231, -0.06777912, -0.06636728, ..., -0.02249136,
          -0.03847423, -0.02195936]]]], dtype=float32), array([[[[-0.03323332, -0.02071491, -0.01761204, ..., -0.16037038,
          -0.12294795, -0.07957492],
         [-0.02232424, -0.01936911, -0.03079141, ..., -0.1692693 ,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1c1516840>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[ 2.1025045e-02,  2.9226732e-02,  3.6879294e-02, ...,
           3.8969159e-02,  3.9983466e-02,  4.1374877e-02],
         [ 1.0867068e-02,  1.9877313e-02,  2.8394803e-02, ...,
           3.8879037e-02,  4.0458471e-02,  4.2434182e-02],
         [-8.4304535e-05,  9.8917987e-03,  1.9426605e-02, ...,
           4.1213609e-02,  4.3147784e-02,  4.5468833e-02],
         ...,
         [-4.9536698e-03, -1.0210590e-02, -1.4964095e-02, ...,
          -4.2402335e-02, -4.0690064e-02, -3.8578771e-02],
         [ 2.6895924e-04, -5.4545305e-03, -1.0745468e-02, ...,
          -4.3789830e-02, -4.1655332e-02, -3.9144650e-02],
         [ 5.8954805e-03, -2.6548575e-04, -5.9706210e-03, ...,
          -4.6739619e-02, -4.4614922e-02, -4.2084157e-02]]]],
      dtype=float32), array([[[[ 0.04313977,  0.04526053,  0.04770144, ...,  0.13992995,
   
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1c1135bf8>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]]), array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]]), array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]])], [array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ...
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1c10abae8>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[-0.07199069, -0.07081825, -0.07107205, ..., -0.10656134,
          -0.0984397 , -0.08952458],
         [-0.07307674, -0.07230391, -0.07292464, ..., -0.10072634,
          -0.09241737, -0.08334494],
         [-0.07438672, -0.07418774, -0.07523069, ..., -0.09512505,
          -0.08667231, -0.07752284],
         ...,
         [-0.03138305, -0.03179662, -0.03238766, ...,  0.00313735,
           0.0097228 ,  0.01490286],
         [-0.02817389, -0.02863522, -0.02934922, ...,  0.00313102,
           0.00920297,  0.01388607],
         [-0.02483108, -0.02531281, -0.02607629, ...,  0.00293021,
           0.00844954,  0.01258484]]]], dtype=float32), array([[[[-8.0173567e-02, -7.1526937e-02, -6.5221108e-02, ...,
          -1.9689843e-01, -1.9982460e-01, -2.0278448e-01],
         [-7.4007541e-02, -6.5698296e-02, -6.0028791e-02, ...,
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1c1c0c048>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]]), array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]]), array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]])], [array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ...
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1c1380ea0>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]]), array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]]), array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]])], [array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ...
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1c1050bf8>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[ 0.05178409,  0.05743577,  0.06334715, ...,  0.1754149 ,
           0.18658267,  0.19734773],
         [ 0.05876968,  0.06489012,  0.07115628, ...,  0.1650819 ,
           0.1759165 ,  0.19205876],
         [ 0.06625752,  0.07279345,  0.07934383, ...,  0.1528603 ,
           0.16079512,  0.17402919],
         ...,
         [ 0.0817139 ,  0.07938163,  0.07664248, ..., -0.00294678,
           0.00202445,  0.01008276],
         [ 0.0800826 ,  0.07775249,  0.07528102, ..., -0.00232896,
           0.00143181,  0.00289747],
         [ 0.07797963,  0.07569324,  0.07332444, ..., -0.00233005,
          -0.00109413,  0.00600498]]]], dtype=float32), array([[[[ 0.23991181,  0.20178702,  0.09660293, ...,  0.04974436,
           0.05320862,  0.06840067],
         [ 0.22194521,  0.14058648,  0.03702856, ...,  0.03738082,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1c1060e18>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[ 0.04683019,  0.04406391,  0.03947945, ...,  0.05523274,
           0.05235778,  0.05045482],
         [ 0.04050721,  0.03735998,  0.03367937, ...,  0.06133916,
           0.0580696 ,  0.05568478],
         [ 0.03437859,  0.03202616,  0.02917242, ...,  0.0679563 ,
           0.06420383,  0.0614438 ],
         ...,
         [ 0.03501183,  0.03712939,  0.03702918, ..., -0.03858453,
          -0.03830861, -0.03545093],
         [ 0.03115037,  0.03132266,  0.02913162, ..., -0.02801701,
          -0.02948867, -0.02961153],
         [ 0.02154663,  0.0186452 ,  0.01215624, ..., -0.01512535,
          -0.01803093, -0.01982981]]]], dtype=float32), array([[[[ 0.05016186,  0.05117255,  0.05272531, ...,  0.        ,
           0.        ,  0.        ],
         [ 0.05487972,  0.05566038,  0.05732747, ...,  0.        ,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1c10342f0>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[-0.0184527 , -0.01500855, -0.01124226, ...,  0.07260633,
           0.07459603,  0.07576438],
         [-0.01428417, -0.0106927 , -0.00676463, ...,  0.08429804,
           0.08579408,  0.08634244],
         [-0.00989769, -0.00615357, -0.00214328, ...,  0.09603748,
           0.09683201,  0.09655994],
         ...,
         [ 0.0196379 ,  0.02681904,  0.03030206, ..., -0.18075553,
          -0.17542486, -0.16809614],
         [ 0.01909863,  0.02468457,  0.0257632 , ..., -0.17771295,
          -0.17129959, -0.16387823],
         [ 0.01803697,  0.02162716,  0.02036548, ..., -0.17213137,
          -0.16554436, -0.1584947 ]]]], dtype=float32), array([[[[ 0.07609189,  0.07556622,  0.07420834, ...,  0.10448297,
           0.10686626,  0.10943806],
         [ 0.0859616 ,  0.0846766 ,  0.08253034, ...,  0.10100666,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1c13b8488>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]]), array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]]), array([[[[1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         ...,
         [1., 1., 0., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.],
         [1., 1., 1., ..., 0., 0., 0.]]]])], [array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ...
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1c1e3e730>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[-0.05712036, -0.05958486, -0.06276969, ..., -0.11689836,
          -0.11552512, -0.11519031],
         [-0.05247063, -0.05559107, -0.05844884, ..., -0.12046255,
          -0.12024003, -0.12071384],
         [-0.04824136, -0.05187213, -0.0554337 , ..., -0.12277877,
          -0.12360214, -0.1246627 ],
         ...,
         [-0.00425708,  0.00203819,  0.00718657, ..., -0.08869812,
          -0.09010158, -0.09093654],
         [-0.00609124,  0.0005193 ,  0.00622181, ..., -0.0854967 ,
          -0.08605479, -0.08587556],
         [-0.00856096, -0.00187659,  0.00420092, ..., -0.08192843,
          -0.08189902, -0.08091048]]]], dtype=float32), array([[[[-0.11553783, -0.11625315, -0.11709726, ...,  0.05523274,
           0.05235778,  0.05045482],
         [-0.12153914, -0.12264635, -0.1239889 , ...,  0.06133916,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1c1e13a60>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[-0.11092547, -0.12279901, -0.13455817, ..., -0.10680291,
          -0.1166895 , -0.10799987],
         [-0.11382717, -0.12622958, -0.13831164, ..., -0.08566464,
          -0.10650966, -0.1125359 ],
         [-0.11699767, -0.1298479 , -0.14218104, ..., -0.0631936 ,
          -0.08590594, -0.10245037],
         ...,
         [-0.11530054, -0.10789612, -0.10038856, ..., -0.07741893,
          -0.08317551, -0.05682141],
         [-0.1114285 , -0.10409936, -0.0967957 , ..., -0.07989013,
          -0.08963177, -0.07664022],
         [-0.10786621, -0.10066657, -0.09353971, ..., -0.07615369,
          -0.08683681, -0.08030752]]]], dtype=float32), array([[[[-0.1063958 , -0.06158843, -0.03921935, ...,  0.2050548 ,
           0.21461184,  0.2246458 ],
         [-0.12004904, -0.04265227, -0.0288188 , ...,  0.20273764,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.169:39660 remote=tcp://172.30.100.1:40264>
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1affbf400>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[-0.09263399, -0.09297062, -0.0938186 , ..., -0.18628956,
          -0.18663031, -0.18675183],
         [-0.09645999, -0.09700651, -0.09794543, ..., -0.1868588 ,
          -0.1867592 , -0.18644193],
         [-0.10026523, -0.10097252, -0.10196032, ..., -0.18736891,
          -0.18676758, -0.18595274],
         ...,
         [-0.17586806, -0.17654334, -0.17897755, ...,  0.00061618,
           0.01330249,  0.0253862 ],
         [-0.17687748, -0.17808576, -0.18131468, ...,  0.00415745,
           0.01649344,  0.02816812],
         [-0.17822357, -0.18010397, -0.18422966, ...,  0.00706568,
           0.01882476,  0.0296592 ]]]], dtype=float32), array([[[[-0.18677397, -0.1867868 , -0.18683696, ...,  0.02595438,
           0.02867979,  0.03168772],
         [-0.18601675, -0.18559283, -0.18524963, ...,  0.02290359,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2ae1c12e9950>, (<function concrete at 0x2ae13185fa60>, [[[[array([[[[-0.06062888, -0.07302027, -0.0843448 , ...,  0.11760552,
           0.15079963,  0.18167186],
         [-0.06439988, -0.07668419, -0.08686469, ...,  0.13556178,
           0.17163165,  0.20832442],
         [-0.06788316, -0.08002497, -0.08871111, ...,  0.17725876,
           0.23212059,  0.26793137],
         ...,
         [ 0.0723215 ,  0.07142564,  0.0712153 , ...,  0.1422724 ,
           0.08223558,  0.05244392],
         [ 0.0744947 ,  0.07307132,  0.07231243, ...,  0.13781865,
           0.07794927,  0.05110458],
         [ 0.07660558,  0.07466903,  0.07333686, ...,  0.12836035,
           0.07843922,  0.05598457]]]], dtype=float32), array([[[[ 0.20313403,  0.21928495,  0.23502725, ..., -0.02597564,
          -0.01962088, -0.01481292],
         [ 0.2281956 ,  0.21221136,  0.22814085, ..., -0.03001569,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.169:39658 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.169:39656 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.169:39654 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.169:39910 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.169:39784 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.169:39864 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.169:39916 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.169:39794 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.169:39790 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.169:39788 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.169:39840 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.169:39792 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.169:39616 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.169:39782 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.169:39908 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.169:39670 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.169:39614 remote=tcp://172.30.100.1:40264>
distributed.utils_perf - INFO - full garbage collection released 11.63 MB from 850 reference cycles (threshold: 10.00 MB)
slurmstepd: error: *** JOB 8988023 ON n2400 CANCELLED AT 2020-01-27T17:19:46 DUE TO TIME LIMIT ***
