/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:46817'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:46068'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:35910'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:38796'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:42178'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:40353'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:38990'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:43018'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:41617'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:40027'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:45353'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:44414'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:44755'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:35978'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:36772'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:33409'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:38797'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:37980'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:46533'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:42351'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:40246'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:33954'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:45087'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:38898'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:41657'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:33777'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:39138'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.5.177:35847'
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:33219
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:44935
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:33219
distributed.worker - INFO -              nanny at:         172.30.5.177:41617
distributed.worker - INFO -              bokeh at:         172.30.5.177:38825
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:45491
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:44935
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:45491
distributed.worker - INFO -              nanny at:         172.30.5.177:44755
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -              bokeh at:         172.30.5.177:45351
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -              nanny at:         172.30.5.177:40246
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-303vpif9
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              bokeh at:         172.30.5.177:38455
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-qz1npc74
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-kcqmgppt
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:40854
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:40854
distributed.worker - INFO -              nanny at:         172.30.5.177:33409
distributed.worker - INFO -              bokeh at:         172.30.5.177:43201
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-xor1kqi1
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:36036
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:36036
distributed.worker - INFO -              nanny at:         172.30.5.177:46068
distributed.worker - INFO -              bokeh at:         172.30.5.177:38930
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-gzxbp3fb
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:45383
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:45383
distributed.worker - INFO -              nanny at:         172.30.5.177:40353
distributed.worker - INFO -              bokeh at:         172.30.5.177:32954
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:33721
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:33721
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-hxa7960r
distributed.worker - INFO -              nanny at:         172.30.5.177:40027
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              bokeh at:         172.30.5.177:45941
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-z8bivi9y
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:34216
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:34216
distributed.worker - INFO -              nanny at:         172.30.5.177:45087
distributed.worker - INFO -              bokeh at:         172.30.5.177:38057
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-9u1oss0b
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:42171
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:42171
distributed.worker - INFO -              nanny at:         172.30.5.177:42178
distributed.worker - INFO -              bokeh at:         172.30.5.177:34780
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-gs83o0_r
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:46567
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:46567
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:45635
distributed.worker - INFO -              nanny at:         172.30.5.177:39138
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:45635
distributed.worker - INFO -              nanny at:         172.30.5.177:38797
distributed.worker - INFO -              bokeh at:         172.30.5.177:39361
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO -              bokeh at:         172.30.5.177:44683
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-_9reoqf2
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-c77vxiti
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:43189
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:43189
distributed.worker - INFO -              nanny at:         172.30.5.177:38796
distributed.worker - INFO -              bokeh at:         172.30.5.177:45117
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:40236
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:40236
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-lm_cdw0a
distributed.worker - INFO -              nanny at:         172.30.5.177:43018
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              bokeh at:         172.30.5.177:45202
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-i1ee8ckp
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:42649
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:42649
distributed.worker - INFO -              nanny at:         172.30.5.177:35978
distributed.worker - INFO -              bokeh at:         172.30.5.177:44177
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-c7ew764_
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:45636
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:45636
distributed.worker - INFO -              nanny at:         172.30.5.177:37980
distributed.worker - INFO -              bokeh at:         172.30.5.177:43036
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-26wis7yy
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:39521
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:39521
distributed.worker - INFO -              nanny at:         172.30.5.177:35910
distributed.worker - INFO -              bokeh at:         172.30.5.177:37827
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-iv3v6fbt
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:43292
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:43292
distributed.worker - INFO -              nanny at:         172.30.5.177:46817
distributed.worker - INFO -              bokeh at:         172.30.5.177:43789
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-huufuyxm
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:45172
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:45172
distributed.worker - INFO -              nanny at:         172.30.5.177:33954
distributed.worker - INFO -              bokeh at:         172.30.5.177:46318
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-0xpttlhl
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:36264
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:36264
distributed.worker - INFO -              nanny at:         172.30.5.177:41657
distributed.worker - INFO -              bokeh at:         172.30.5.177:40297
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-e9yp9fb4
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:39725
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:39725
distributed.worker - INFO -              nanny at:         172.30.5.177:35847
distributed.worker - INFO -              bokeh at:         172.30.5.177:36142
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:33422
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-rpa9noa0
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:33422
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:         172.30.5.177:44414
distributed.worker - INFO -              bokeh at:         172.30.5.177:34536
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-0uvp4lkq
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:46871
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:46871
distributed.worker - INFO -              nanny at:         172.30.5.177:42351
distributed.worker - INFO -              bokeh at:         172.30.5.177:45882
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-9ueeehj1
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:45814
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:45814
distributed.worker - INFO -              nanny at:         172.30.5.177:46533
distributed.worker - INFO -              bokeh at:         172.30.5.177:38522
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-rwyr0eqj
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:37307
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:37307
distributed.worker - INFO -              nanny at:         172.30.5.177:38898
distributed.worker - INFO -              bokeh at:         172.30.5.177:46247
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-mtd9x7j9
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:42398
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:42398
distributed.worker - INFO -              nanny at:         172.30.5.177:33777
distributed.worker - INFO -              bokeh at:         172.30.5.177:45247
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-xf9w8rv8
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:38586
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:38586
distributed.worker - INFO -              nanny at:         172.30.5.177:38990
distributed.worker - INFO -              bokeh at:         172.30.5.177:46008
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-9rsbh6nc
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:41709
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:41709
distributed.worker - INFO -              nanny at:         172.30.5.177:45353
distributed.worker - INFO -              bokeh at:         172.30.5.177:39166
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-kaqqckhe
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.5.177:46092
distributed.worker - INFO -          Listening to:   tcp://172.30.5.177:46092
distributed.worker - INFO -              nanny at:         172.30.5.177:36772
distributed.worker - INFO -              bokeh at:         172.30.5.177:34009
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-ku1scp0q
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2afe95de1240>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2afe95de1240>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2afe95de1240>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2afe95de1240>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2afe95de1240>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2afe95de1240>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2afe95de1240>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2afe95de1240>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2afe95de1240>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45148 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45282 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45296 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45292 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45390 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45380 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45392 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45178 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45288 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45376 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45276 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45372 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45274 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45362 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45286 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45378 remote=tcp://172.30.100.2:44717>
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2afe95de1240>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2afe95de1240>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45298 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45386 remote=tcp://172.30.100.2:44717>
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.worker - WARNING - Heartbeat to scheduler failed
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.worker - WARNING - Heartbeat to scheduler failed
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45122 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45236 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45358 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45104 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45112 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45264 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45350 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45406 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45460 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45204 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45950 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45149 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45260 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45348 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45408 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45462 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45480 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45203 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45954 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45262 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45354 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45410 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45464 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45478 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45208 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45956 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45190 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45356 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45412 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45210 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45266 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45958 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45162 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45280 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45366 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45106 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45284 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45374 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45114 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45156 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45294 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45384 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45130 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45238 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45468 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45134 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:46018 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45138 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45194 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45248 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:46022 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45150 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45290 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45382 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45124 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45230 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45400 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45144 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45198 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45254 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45368 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45118 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45258 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45352 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45404 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45458 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45206 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45952 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45132 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45240 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45120 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45234 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45388 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45128 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45242 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45444 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45160 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45364 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45108 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45146 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45200 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45256 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45402 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45948 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45469 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45136 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:46020 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45116 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45140 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45192 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45252 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:46024 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45158 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45278 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45370 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45110 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45360 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45142 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45196 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45250 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:46026 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45126 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.5.177:45232 remote=tcp://172.30.100.2:44717>
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:39521
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:45636
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:45814
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:34216
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:36036
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:43189
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:33219
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:42649
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:43292
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:46567
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:36264
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:45383
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:33422
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:39725
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:35910'
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:40236
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:42398
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:40854
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:38586
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:46871
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:45172
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:42171
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:46533'
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:37307
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:41709
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:46092
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:45635
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:45491
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:37980'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:45087'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:46068'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:38796'
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:33721
distributed.worker - INFO - Stopping worker at tcp://172.30.5.177:44935
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:41617'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:35978'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:46817'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:39138'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:35847'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:44414'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:33409'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:33777'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:38990'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:42351'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:43018'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:33954'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:36772'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:41657'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:40246'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:38797'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:40353'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:45353'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:42178'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:38898'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:40027'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.5.177:44755'
distributed.dask_worker - INFO - End worker
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
