/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:41308'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:39042'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:34275'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:44053'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:39055'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:44175'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:32870'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:37275'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:38994'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:42202'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:37753'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:44805'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:37389'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:46559'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:41928'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:39061'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:45849'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:46646'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:34796'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:44071'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:36836'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:43832'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:36295'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:39088'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:44315'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:46125'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:37998'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.10.102:36171'
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:34707
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:34707
distributed.worker - INFO -              nanny at:        172.30.10.102:41928
distributed.worker - INFO -              bokeh at:        172.30.10.102:38661
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-bz3tnlwq
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:40389
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:40389
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:38677
distributed.worker - INFO -              nanny at:        172.30.10.102:44805
distributed.worker - INFO -              bokeh at:        172.30.10.102:33861
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:38677
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO -              nanny at:        172.30.10.102:42202
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              bokeh at:        172.30.10.102:42400
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-h7ey3z1u
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-igm4l255
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:41197
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:41197
distributed.worker - INFO -              nanny at:        172.30.10.102:46646
distributed.worker - INFO -              bokeh at:        172.30.10.102:36138
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-d4xe2e22
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:41943
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:41943
distributed.worker - INFO -              nanny at:        172.30.10.102:37753
distributed.worker - INFO -              bokeh at:        172.30.10.102:41309
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-j7sde3yn
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:46006
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:46006
distributed.worker - INFO -              nanny at:        172.30.10.102:34275
distributed.worker - INFO -              bokeh at:        172.30.10.102:33038
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-f4vtkl5k
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:33383
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:33383
distributed.worker - INFO -              nanny at:        172.30.10.102:38994
distributed.worker - INFO -              bokeh at:        172.30.10.102:33039
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-51o2mayd
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:44913
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:44913
distributed.worker - INFO -              nanny at:        172.30.10.102:44071
distributed.worker - INFO -              bokeh at:        172.30.10.102:33682
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-jvj0fqxf
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:44252
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:44252
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:        172.30.10.102:37389
distributed.worker - INFO -              bokeh at:        172.30.10.102:40184
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -               Threads:                          1
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:33215
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-r5hm8nh2
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:33215
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:        172.30.10.102:36171
distributed.worker - INFO -              bokeh at:        172.30.10.102:36695
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-m3p350jb
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:38275
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:38275
distributed.worker - INFO -              nanny at:        172.30.10.102:44175
distributed.worker - INFO -              bokeh at:        172.30.10.102:42078
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-__drkv0p
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:34107
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:34107
distributed.worker - INFO -              nanny at:        172.30.10.102:39088
distributed.worker - INFO -              bokeh at:        172.30.10.102:46563
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-urmpel10
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:36415
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:36415
distributed.worker - INFO -              nanny at:        172.30.10.102:45849
distributed.worker - INFO -              bokeh at:        172.30.10.102:39038
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-weoojn5j
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:43552
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:43552
distributed.worker - INFO -              nanny at:        172.30.10.102:37275
distributed.worker - INFO -              bokeh at:        172.30.10.102:35972
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-5lazdrwh
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:37448
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:37448
distributed.worker - INFO -              nanny at:        172.30.10.102:44315
distributed.worker - INFO -              bokeh at:        172.30.10.102:33185
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-b7l8j57o
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:33187
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:33187
distributed.worker - INFO -              nanny at:        172.30.10.102:32870
distributed.worker - INFO -              bokeh at:        172.30.10.102:33099
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-kt173xnz
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:41237
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:41237
distributed.worker - INFO -              nanny at:        172.30.10.102:41308
distributed.worker - INFO -              bokeh at:        172.30.10.102:40067
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-r6hw6hor
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:42179
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:42179
distributed.worker - INFO -              nanny at:        172.30.10.102:44053
distributed.worker - INFO -              bokeh at:        172.30.10.102:42344
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-pdj1wsc4
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:36191
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:36191
distributed.worker - INFO -              nanny at:        172.30.10.102:43832
distributed.worker - INFO -              bokeh at:        172.30.10.102:36087
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-hur4uwbm
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:37141
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:37141
distributed.worker - INFO -              nanny at:        172.30.10.102:34796
distributed.worker - INFO -              bokeh at:        172.30.10.102:37070
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-m9n409bw
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:43326
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:43326
distributed.worker - INFO -              nanny at:        172.30.10.102:46125
distributed.worker - INFO -              bokeh at:        172.30.10.102:42608
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-0y9hi226
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:43504
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:43504
distributed.worker - INFO -              nanny at:        172.30.10.102:36295
distributed.worker - INFO -              bokeh at:        172.30.10.102:33086
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-2mgntn9_
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:44178
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:44178
distributed.worker - INFO -              nanny at:        172.30.10.102:39055
distributed.worker - INFO -              bokeh at:        172.30.10.102:42956
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-tilvkmt_
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:38387
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:38387
distributed.worker - INFO -              nanny at:        172.30.10.102:36836
distributed.worker - INFO -              bokeh at:        172.30.10.102:44095
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-u_v1sg2t
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:43267
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:43267
distributed.worker - INFO -              nanny at:        172.30.10.102:39061
distributed.worker - INFO -              bokeh at:        172.30.10.102:46131
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-sk5bjk4d
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:45553
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:45553
distributed.worker - INFO -              nanny at:        172.30.10.102:39042
distributed.worker - INFO -              bokeh at:        172.30.10.102:34038
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-2gr099y3
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:33548
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:33548
distributed.worker - INFO -              nanny at:        172.30.10.102:46559
distributed.worker - INFO -              bokeh at:        172.30.10.102:39931
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-y5pivy1z
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:  tcp://172.30.10.102:43135
distributed.worker - INFO -          Listening to:  tcp://172.30.10.102:43135
distributed.worker - INFO -              nanny at:        172.30.10.102:37998
distributed.worker - INFO -              bokeh at:        172.30.10.102:38245
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-byup4y8t
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:40634 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:40722 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:40828 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:40832 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2abd3e24b208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2abd3e24b208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2abd3e24b208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41036 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41090 remote=tcp://172.30.100.2:37747>
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2abd3e24b208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2abd3e24b208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41224 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41256 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:40932 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41048 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:40838 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2abd3e24b208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2abd3e24b208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2abd3e24b208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:40724 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:40938 remote=tcp://172.30.100.2:37747>
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2abd3e24b208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2abd3e24b208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2abd3e24b208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41230 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41104 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41222 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2abd3e24b208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2abd3e24b208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2abd3e24b208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2abd3e24b208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41420 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41472 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41422 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41466 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:40830 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:40980 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:40988 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:40978 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41046 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41374 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41470 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41600 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41468 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41604 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:40984 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41042 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41612 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41428 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41452 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41220 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41044 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41456 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41494 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41130 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41617 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41286 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41314 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:40836 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41426 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41478 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41154 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41556 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41280 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41340 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41392 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41460 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41488 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41614 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41630 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41284 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41346 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41096 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41462 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41136 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41290 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:40834 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:40886 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41430 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41088 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41476 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41152 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41278 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41342 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41412 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41562 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41606 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41404 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41648 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41066 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41194 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41276 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41332 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41372 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41410 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41846 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41596 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41106 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41506 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41544 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41184 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41266 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41360 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41836 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41598 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41642 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41444 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41102 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41108 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41508 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41546 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41268 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41838 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41644 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41450 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41146 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41548 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41190 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41272 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41336 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41366 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41842 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41522 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41530 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41586 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41100 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:40976 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41504 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41542 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41264 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41326 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41358 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41378 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41386 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41408 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41594 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41834 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41454 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41490 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41248 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41632 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41310 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41348 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41520 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41094 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41458 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41492 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41132 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41616 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41288 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41312 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41526 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41084 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41092 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41486 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41246 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41316 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41516 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41464 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41496 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41138 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41560 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41400 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41534 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41588 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41080 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41098 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41502 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41540 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41182 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41262 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41418 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41208 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41484 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41574 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41244 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41344 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41416 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41514 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41818 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41148 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41550 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41188 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41270 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41364 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41844 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41480 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41124 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41512 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41160 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41204 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41070 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41156 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41376 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41564 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41076 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41254 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41394 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41532 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41584 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:40884 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41068 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41158 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41414 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41566 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41078 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41082 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41498 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41536 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41258 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41292 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41324 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41590 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41602 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41646 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41150 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41554 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41192 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41274 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41334 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41370 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41848 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41424 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41474 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:40986 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41650 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41086 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41448 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41110 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41552 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41186 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41320 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41330 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41368 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41840 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41500 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41538 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41180 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41260 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41402 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41592 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41558 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41252 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41398 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41396 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41528 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41582 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41482 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41572 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41206 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41282 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41816 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41250 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41380 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41524 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41580 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41518 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41568 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.10.102:41814 remote=tcp://172.30.100.2:37747>
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.utils_perf - INFO - full garbage collection released 51.40 MB from 7744 reference cycles (threshold: 10.00 MB)
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:46006
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:36415
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:44913
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:34275'
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:44178
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:41237
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:44071'
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:33187
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:38677
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:45553
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:45849'
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:33383
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:34107
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:39055'
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:41197
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:41308'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:32870'
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:36191
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:43267
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:38387
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:43504
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:38275
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:44252
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:34707
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:43135
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:33215
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:42179
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:33548
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:42202'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:39042'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:39088'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:38994'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:46646'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:43832'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:39061'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:36836'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:44175'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:37389'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:36295'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:41928'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:37998'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:36171'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:46559'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:44053'
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:37448
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:44315'
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:40389
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:41943
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:44805'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:37753'
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:43326
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:46125'
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:37141
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:34796'
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Stopping worker at tcp://172.30.10.102:43552
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.10.102:37275'
distributed.dask_worker - INFO - End worker
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
